# 📘 Programação para Ciência de Dados – MBA Ciência de Dados, Universidade de Fortaleza

**Professor:** Cássio Pinheiro  
**Carga horária:** 28h  
**Formato:** Intensivo  
**Linguagem:** Python  
**Ambiente:** Jupyter Notebook / Google Colab

Este notebook integra os três primeiros módulos da disciplina **Programação para Ciência de Dados**, combinando teoria técnica, exemplos práticos detalhados e desafios aplicados usando datasets reais.

---

## 📑 Índice

1. [Módulo 1 - Fundamentos de Programação com Python](#modulo1)
2. [Módulo 2 - Manipulação Avançada com Pandas e NumPy](#modulo2)
3. [Módulo 3 - Visualização e Análise Exploratória de Dados](#modulo3)

<a id='modulo1'></a>
# 🧩 Módulo 1 – Fundamentos de Programação com Python

Neste módulo, abordamos a base da linguagem Python aplicada à ciência de dados.  
Exploramos tipos de dados, operações, estruturas de controle, funções avançadas, tratamento de erros e boas práticas.

## 1.1 Tipos de Dados, Operações e Conversões

In [ ]:
# Tipos primitivos e verificação de tipos
inteiro = 42
decimal = 3.14159
texto = "Ciência de Dados"
booleano = True
nulo = None

for var, nome in [(inteiro, 'inteiro'), (decimal, 'decimal'), 
                   (texto, 'texto'), (booleano, 'booleano'), (nulo, 'nulo')]:
    print(f"{nome:>10} = {str(var):>20}  │  tipo: {type(var).__name__}")

In [ ]:
# Operações aritméticas
x, y = 10, 3

operacoes = {
    'Soma': x + y,
    'Subtração': x - y,
    'Multiplicação': x * y,
    'Divisão real': round(x / y, 4),
    'Divisão inteira': x // y,
    'Módulo (resto)': x % y,
    'Potência': x ** y,
}

for op, resultado in operacoes.items():
    print(f"{op:>20}: {resultado}")

In [ ]:
# Conversões de tipo (casting)
valor_str = "123"
valor_int = int(valor_str)
valor_float = float(valor_str)

print(f"String → int: '{valor_str}' → {valor_int}  (tipo: {type(valor_int).__name__})")
print(f"String → float: '{valor_str}' → {valor_float}  (tipo: {type(valor_float).__name__})")
print(f"int → bool: 0 → {bool(0)}, 1 → {bool(1)}, -5 → {bool(-5)}")
print(f"str → bool: '' → {bool('')}, 'abc' → {bool('abc')}")

# Strings: métodos úteis para limpeza de dados
texto = "  Ciência de Dados - UNIFOR  "
print(f"\nOriginal:    '{texto}'")
print(f"strip():     '{texto.strip()}'")
print(f"lower():     '{texto.strip().lower()}'")
print(f"upper():     '{texto.strip().upper()}'")
print(f"replace():   '{texto.strip().replace('UNIFOR', 'Universidade de Fortaleza')}'")
print(f"split('-'):  {texto.strip().split('-')}")
print(f"startswith: {texto.strip().startswith('Ciência')}")

## 1.2 Estruturas de Dados Fundamentais

In [ ]:
# Listas — estrutura ordenada e mutável
numeros = [1, 2, 3, 4, 5]
print("Lista original:", numeros)
print("Primeiro elemento:", numeros[0])
print("Último elemento:", numeros[-1])
print("Slice [1:4]:", numeros[1:4])
print("Passo 2:", numeros[::2])
print("Reverso:", numeros[::-1])

# Operações com listas
numeros.append(6)
numeros.extend([7, 8])
numeros.insert(0, 0)
print("\nApós append/extend/insert:", numeros)

# Ordenação e busca
desordenados = [5, 2, 8, 1, 9, 3]
print(f"\nsorted() (não altera original): {sorted(desordenados)}")
print(f"sorted(reverse=True): {sorted(desordenados, reverse=True)}")
print(f"min={min(desordenados)}, max={max(desordenados)}, sum={sum(desordenados)}")

# Desempacotamento
primeiro, *meio, ultimo = [10, 20, 30, 40, 50]
print(f"\nDesempacotamento: primeiro={primeiro}, meio={meio}, ultimo={ultimo}")

In [ ]:
# Dicionários — pares chave:valor, muito usados em ciência de dados
aluno = {
    'nome': 'Ana Silva',
    'idade': 28,
    'curso': 'MBA Ciência de Dados',
    'notas': [8.5, 9.0, 7.5, 8.0],
    'ativo': True
}

print(f"Nome: {aluno['nome']}")
print(f"Média: {sum(aluno['notas']) / len(aluno['notas']):.2f}")

# Métodos úteis
print(f"\nChaves: {list(aluno.keys())}")
print(f"Valores: {list(aluno.values())}")

# .get() com valor padrão — evita KeyError
print(f"Email: {aluno.get('email', 'Não informado')}")

# Atualizar e adicionar
aluno['email'] = 'ana@email.com'
aluno.update({'telefone': '85 99999-0000', 'cidade': 'Fortaleza'})

print("\nDicionário atualizado:")
for chave, valor in aluno.items():
    print(f"  {chave}: {valor}")

In [ ]:
# Tuplas — imutáveis, ideais para dados que não devem mudar
coordenadas = (10.5, 20.3)
x, y = coordenadas
print(f"Coordenadas: X={x}, Y={y}")

# Named Tuples — tuplas com nomes de campo
from collections import namedtuple
Ponto = namedtuple('Ponto', ['x', 'y', 'z'])
p = Ponto(1.0, 2.5, 3.7)
print(f"Ponto: x={p.x}, y={p.y}, z={p.z}")

# Sets — coleções sem duplicatas, operações de conjunto
set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}

print(f"\nUnião (|):        {set_a | set_b}")
print(f"Interseção (&):    {set_a & set_b}")
print(f"Diferença A-B:     {set_a - set_b}")
print(f"Diferença B-A:     {set_b - set_a}")
print(f"Dif. simétrica (^): {set_a ^ set_b}")

# Caso prático: remover duplicatas preservando ordem
lista_com_duplicatas = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
unicos = list(dict.fromkeys(lista_com_duplicatas))
print(f"\nCom duplicatas: {lista_com_duplicatas}")
print(f"Sem duplicatas: {unicos}")

## 1.3 Estruturas de Controle

In [ ]:
# Condicionais e laços
valores = [10, 15, 20, 25, 30]

for v in valores:
    if v % 2 == 0:
        print(f"{v} é par")
    else:
        print(f"{v} é ímpar")

# Operador ternário
x = 42
paridade = "par" if x % 2 == 0 else "ímpar"
print(f"\n{x} é {paridade}")

# Enumerate — índice + valor
frutas = ['maçã', 'banana', 'laranja', 'uva']
print("\nFrutas com índice:")
for i, fruta in enumerate(frutas, start=1):
    print(f"  {i}. {fruta}")

# Zip — iterar em paralelo
nomes = ['Ana', 'Bruno', 'Carla']
notas = [9.5, 7.8, 8.2]
for nome, nota in zip(nomes, notas):
    print(f"  {nome}: {nota}")

# While com condição de parada
contador = 0
soma = 0
while contador < 5:
    soma += contador
    contador += 1
print(f"\nSoma de 0 a 4: {soma}")

In [ ]:
# For/else, break, continue — controle refinado de laços
print("Buscando primeiro número divisível por 7 entre 50 e 100:")
for n in range(50, 101):
    if n % 7 == 0:
        print(f"  Encontrado: {n}")
        break
else:
    print("  Nenhum encontrado")

print("\nNúmeros de 1 a 10, pulando múltiplos de 3:")
resultado = []
for n in range(1, 11):
    if n % 3 == 0:
        continue
    resultado.append(n)
print(f"  {resultado}")

## 1.4 Compreensões e Programação Funcional

In [ ]:
# List Comprehension — sintaxe concisa para criar listas
quadrados = [x**2 for x in range(1, 11)]
print("Quadrados:", quadrados)

# Com condição (filtro)
pares = [x for x in quadrados if x % 2 == 0]
print("Apenas pares:", pares)

# Compreensão aninhada — achatar listas
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
achatada = [elem for linha in matriz for elem in linha]
print("Matriz achatada:", achatada)

# Dict Comprehension
quadrados_dict = {x: x**2 for x in range(1, 6)}
print("Dict de quadrados:", quadrados_dict)

# Dict Comprehension com inversão chave-valor
original = {'a': 1, 'b': 2, 'c': 3}
invertido = {v: k for k, v in original.items()}
print(f"Original: {original} → Invertido: {invertido}")

# Set Comprehension
vogais = {letra.lower() for palavra in ['Python', 'Data', 'Science'] 
          for letra in palavra if letra.lower() in 'aeiou'}
print("Vogais únicas:", vogais)

In [ ]:
# Funções lambda e funções de alta ordem: map, filter, reduce
from functools import reduce

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# map — aplica função a cada elemento
dobrados = list(map(lambda x: x * 2, numeros))
print("map (dobro):", dobrados)

# filter — filtra elementos por condição
pares = list(filter(lambda x: x % 2 == 0, numeros))
print("filter (pares):", pares)

# reduce — acumula resultado
produto = reduce(lambda acc, x: acc * x, numeros)
print(f"reduce (produto): {produto}")

# Combinação: pipeline funcional
resultado = reduce(
    lambda acc, x: acc + x,
    map(lambda x: x**2, filter(lambda x: x % 2 == 0, numeros))
)
print(f"\nPipeline (soma dos quadrados dos pares): {resultado}")

# sorted com key — ordenação customizada
alunos = [('Ana', 9.5), ('Bruno', 7.8), ('Carla', 8.9), ('Diego', 6.5)]
por_nota = sorted(alunos, key=lambda a: a[1], reverse=True)
print(f"\nRanking por nota: {por_nota}")

## 1.5 Funções Avançadas

In [ ]:
# Função com docstring, argumentos padrão e type hints
def calcular_estatisticas(dados: list, incluir_media: bool = True, 
                          incluir_mediana: bool = False) -> dict:
    """
    Calcula estatísticas básicas de uma lista de números.
    
    Args:
        dados: Lista de números
        incluir_media: Se True, calcula a média
        incluir_mediana: Se True, calcula a mediana
    
    Returns:
        Dicionário com as estatísticas calculadas
    
    Raises:
        ValueError: Se a lista estiver vazia
    """
    if not dados:
        raise ValueError("A lista de dados não pode estar vazia")
    
    resultado = {
        'minimo': min(dados),
        'maximo': max(dados),
        'amplitude': max(dados) - min(dados),
        'quantidade': len(dados),
        'soma': sum(dados)
    }
    
    if incluir_media:
        resultado['media'] = sum(dados) / len(dados)
    
    if incluir_mediana:
        dados_ordenados = sorted(dados)
        n = len(dados_ordenados)
        if n % 2 == 0:
            resultado['mediana'] = (dados_ordenados[n//2-1] + dados_ordenados[n//2]) / 2
        else:
            resultado['mediana'] = dados_ordenados[n//2]
    
    return resultado

dados = [10, 20, 30, 40, 50, 15, 25, 35]
stats = calcular_estatisticas(dados, incluir_mediana=True)
for chave, valor in stats.items():
    print(f"  {chave}: {valor}")

In [ ]:
# *args e **kwargs — flexibilidade em parâmetros
def relatorio_vendas(titulo, *produtos, **detalhes):
    """Gera um relatório flexível que aceita número variável de argumentos."""
    print(f"\n{'='*50}")
    print(f"  {titulo}")
    print(f"{'='*50}")
    
    if produtos:
        print("\nProdutos vendidos:")
        for i, prod in enumerate(produtos, 1):
            print(f"  {i}. {prod}")
    
    if detalhes:
        print("\nDetalhes adicionais:")
        for chave, valor in detalhes.items():
            print(f"  {chave}: {valor}")

relatorio_vendas(
    "Relatório Mensal - Março/2026",
    "Notebook", "Monitor", "Teclado", "Mouse",
    vendedor="Carlos Silva",
    regiao="Nordeste",
    meta_atingida="92%"
)

In [ ]:
# Decorators — padrão para adicionar comportamento a funções
import time

def medir_tempo(func):
    """Decorator que mede o tempo de execução de uma função."""
    def wrapper(*args, **kwargs):
        inicio = time.time()
        resultado = func(*args, **kwargs)
        fim = time.time()
        print(f"\u23f1 {func.__name__} executou em {fim - inicio:.4f}s")
        return resultado
    return wrapper

@medir_tempo
def processar_dados(n):
    """Simula processamento pesado."""
    return sum(i**2 for i in range(n))

resultado = processar_dados(1_000_000)
print(f"Resultado: {resultado:,}")

## 1.6 Tratamento de Erros e Exceções

In [ ]:
# Try/except/else/finally — tratamento robusto de erros
def converter_para_numero(valor):
    """Converte string para número com tratamento de erros."""
    try:
        resultado = float(valor)
    except ValueError:
        print(f"  \u26a0 '{valor}' não é um número válido")
        return None
    except TypeError:
        print(f"  \u26a0 Tipo inválido: {type(valor).__name__}")
        return None
    else:
        print(f"  \u2713 '{valor}' \u2192 {resultado}")
        return resultado
    finally:
        pass

valores_teste = ["42", "3.14", "abc", "", "1e5"]
print("Convertendo valores:")
resultados = [converter_para_numero(v) for v in valores_teste]
print(f"\nResultados: {resultados}")

In [ ]:
# Exceções customizadas e validação de dados
class DadosInvalidosError(Exception):
    """Exceção para dados de entrada inválidos."""
    pass

def validar_idade(idade):
    if not isinstance(idade, (int, float)):
        raise DadosInvalidosError(f"Idade deve ser numérica, recebeu: {type(idade).__name__}")
    if idade < 0 or idade > 150:
        raise DadosInvalidosError(f"Idade fora do intervalo válido (0-150): {idade}")
    return True

testes = [25, -5, 200, "trinta", 0, 100]
for t in testes:
    try:
        validar_idade(t)
        print(f"  \u2713 {t} \u2192 idade válida")
    except DadosInvalidosError as e:
        print(f"  \u2717 {e}")

## 1.7 Generators e Iteradores

In [ ]:
# Generators — produzem valores sob demanda, economizando memória
import sys

lista_grande = [x**2 for x in range(100_000)]
gen_grande = (x**2 for x in range(100_000))

print(f"Lista: {sys.getsizeof(lista_grande):>10,} bytes")
print(f"Generator: {sys.getsizeof(gen_grande):>7,} bytes")

# Generator function para leitura de dados em lotes
def gerar_lotes(dados, tamanho_lote):
    """Divide dados em lotes de tamanho fixo — útil para big data."""
    for i in range(0, len(dados), tamanho_lote):
        yield dados[i:i + tamanho_lote]

dados = list(range(1, 22))
print(f"\nDados: {dados}")
print(f"Processando em lotes de 5:")
for i, lote in enumerate(gerar_lotes(dados, 5), 1):
    print(f"  Lote {i}: {lote} \u2192 soma = {sum(lote)}")

## 1.8 Manipulação de Arquivos

In [ ]:
# Escrita de arquivo
with open("exemplo.txt", "w", encoding='utf-8') as f:
    f.write("Disciplina: Programação para Ciência de Dados\n")
    f.write("Professor: Cássio Pinheiro\n")
    f.write("Universidade de Fortaleza\n")

# Leitura de arquivo
with open("exemplo.txt", "r", encoding='utf-8') as f:
    conteudo = f.read()
    print(conteudo)

# Leitura linha por linha
with open("exemplo.txt", "r", encoding='utf-8') as f:
    for i, linha in enumerate(f, 1):
        print(f"Linha {i}: {linha.strip()}")

Linha 1: Disciplina: Programação para Ciência de Dados
Linha 2: Professor: Cássio Pinheiro
Linha 3: Universidade de Fortaleza


<a id='modulo2'></a>
# 🧮 Módulo 2 – Manipulação Avançada com Pandas e NumPy

Introdução à manipulação de dados estruturados com as bibliotecas `pandas` e `numpy`.  
Inclui criação de arrays, operações vetorizadas, DataFrames, limpeza, transformação, agregações, joins e operações temporais.

## 2.1 NumPy - Fundamentos

In [6]:
import numpy as np
# Criação de arrays
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
identidade = np.eye(3)
aleatorio = np.random.rand(3, 3)

print("Array 1D:", arr1d)
print("\nArray 2D:\n", arr2d)
print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)

print("\nIdentidade:\n", identidade)
print("\nAleatório:\n", aleatorio)

Array 1D: [1 2 3 4 5]

Array 2D:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Identidade:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Aleatório:
 [[0.40191293 0.98268488 0.18355873]
 [0.3292981  0.15942665 0.13253095]
 [0.13540146 0.24284479 0.01207965]]


In [ ]:
# Operações vetorizadas (muito mais rápidas que loops)
arr = np.array([1, 2, 3, 4, 5])

print("Original:", arr)
print("Multiplicado por 2:", arr * 2)
print("Ao quadrado:", arr ** 2)
print("Mais 10:", arr + 10)

# Operações entre arrays
arr2 = np.array([10, 20, 30, 40, 50])
print("Soma do elemento a elemento:", arr + arr2)
print("Produto elemento a elemento:", arr * arr2)

Original: [1 2 3 4 5]
Multiplicado por 2: [ 2  4  6  8 10]
Ao quadrado: [ 1  4  9 16 25]
Mais 10: [11 12 13 14 15]
Soma de arrays: [11 22 33 44 55]
Produto elemento a elemento: [ 10  40  90 160 250]


In [ ]:
# Broadcasting — operações entre arrays de dimensões diferentes
import numpy as np

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vetor = np.array([10, 20, 30])

print("Matriz:\n", matriz)
print("\nVetor:", vetor)
print("\nMatriz + Vetor (broadcasting):\n", matriz + vetor)
print("\nMatriz * Vetor (broadcasting):\n", matriz * vetor)

# Normalização por coluna (caso real em ML)
media_col = matriz.mean(axis=0)
std_col = matriz.std(axis=0)
normalizado = (matriz - media_col) / std_col
print(f"\nMédias por coluna: {media_col}")
print(f"Desvio por coluna: {std_col.round(2)}")
print(f"Normalizado (z-score):\n{normalizado.round(2)}")

In [7]:
# Indexação e fatiamento
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Indexação booleana
maiores_que_5 = arr[arr > 5]
print("Maiores que 5:", maiores_que_5)

pares = arr[arr % 2 == 0]
print("Pares:", pares)

# Fancy indexing
indices = [0, 2, 4, 6]
elementos = arr[indices]
print("Elementos nos índices [0,2,4,6]:", elementos)

Maiores que 5: [ 6  7  8  9 10]
Pares: [ 2  4  6  8 10]
Elementos nos índices [0,2,4,6]: [1 3 5 7]


In [8]:
# Operações estatísticas
np.random.seed(42)
dados = np.random.randn(1000)

print(f"Média: {np.mean(dados):.4f}")
print(f"Mediana: {np.median(dados):.4f}")
print(f"Desvio padrão: {np.std(dados):.4f}")
print(f"Variância: {np.var(dados):.4f}")
print(f"Mínimo: {np.min(dados):.4f}")
print(f"Máximo: {np.max(dados):.4f}")
print(f"Percentil 25: {np.percentile(dados, 25):.4f}")
print(f"Percentil 75: {np.percentile(dados, 75):.4f}")

Média: 0.0193
Mediana: 0.0253
Desvio padrão: 0.9787
Variância: 0.9579
Mínimo: -3.2413
Máximo: 3.8527
Percentil 25: -0.6476
Percentil 75: 0.6479


In [ ]:
# Reshape, stack e concatenação
arr = np.arange(1, 13)
print("Array original:", arr)

matriz_3x4 = arr.reshape(3, 4)
matriz_4x3 = arr.reshape(4, 3)
print(f"\nReshape 3×4:\n{matriz_3x4}")
print(f"\nReshape 4×3:\n{matriz_4x3}")
print(f"\nTransposta de 3×4:\n{matriz_3x4.T}")

# Concatenação
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f"\nConcatenação: {np.concatenate([a, b])}")
print(f"vstack:\n{np.vstack([a, b])}")
print(f"hstack: {np.hstack([a, b])}")

# Where — seleção condicional (como IF vetorizado)
dados = np.array([85, 42, 73, 91, 56, 68, 95, 38])
categorias = np.where(dados >= 70, 'Aprovado', 'Reprovado')
print(f"\nNotas: {dados}")
print(f"Status: {categorias}")

In [ ]:
# Álgebra linear
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# Multiplicação de matrizes
produto = np.dot(A, B)
print("\nA × B:\n", produto)

# Determinante
det_A = np.linalg.det(A)
print(f"\nDeterminante de A: {det_A}")

# Inversa
inv_A = np.linalg.inv(A)
print("\nInversa de A:\n", inv_A)

# Autovalores e autovetores
autovalores, autovetores = np.linalg.eig(A)
print("\nAutovalores:", autovalores)
print("\nAutovetores:\n", autovetores)

## 2.2 Pandas - Series e DataFrames

O `pandas` é a principal biblioteca para manipulação de dados tabulares em Python.  
Possui dois objetos fundamentais: **Series** (1D) e **DataFrame** (2D).

In [6]:
import pandas as pd

# Series — array unidimensional com rótulos
notas = pd.Series([9.5, 7.8, 8.2, 6.5, 9.0], 
                   index=['Ana', 'Bruno', 'Carla', 'Diego', 'Eva'],
                   name='Notas')
print("Series de notas:")
print(notas)
print(f"\nMédia: {notas.mean():.2f}")
print(f"Mediana: {notas.median():.2f}")
print(f"Desvio padrão: {notas.std():.2f}")

# Filtragem booleana
print(f"\nAprovados (nota >= 7):")
print(notas[notas >= 7])

# Operações vetorizadas em Series
print(f"\nNotas normalizadas (0-100):")
print((notas * 10).round(1))

# value_counts — distribuição de frequências
categorias = pd.cut(notas, bins=[0, 5, 7, 9, 10], labels=['Insuficiente', 'Regular', 'Bom', 'Excelente'])
print(f"\nDistribuição por categoria:")
print(categorias.value_counts())

Series de notas:
Ana      9.5
Bruno    7.8
Carla    8.2
Diego    6.5
Eva      9.0
Name: Notas, dtype: float64

Média: 8.20
Mediana: 8.20
Desvio padrão: 1.16

Aprovados (nota >= 7):
Ana      9.5
Bruno    7.8
Carla    8.2
Eva      9.0
Name: Notas, dtype: float64

Notas normalizadas (0-100):
Ana      95.0
Bruno    78.0
Carla    82.0
Diego    65.0
Eva      90.0
Name: Notas, dtype: float64

Distribuição por categoria:
Notas
Bom             3
Regular         1
Excelente       1
Insuficiente    0
Name: count, dtype: int64


In [ ]:
# Leitura do dataset Titanic
df_titanic = pd.read_csv("datasets/titanic.csv")

print("Primeiras linhas:")
print(df_titanic.head())

print(f"\nShape: {df_titanic.shape} ({df_titanic.shape[0]} linhas × {df_titanic.shape[1]} colunas)")
print(f"\nTipos de dados:")
print(df_titanic.dtypes)

print("\nEstatísticas descritivas:")
print(df_titanic.describe())

print("\nEstatísticas de colunas categóricas:")
print(df_titanic.describe(include='object'))

Primeiras linhas:
   PassengerId  Pclass     Sex        Age        Fare  Survived
0            1       2  female   9.299793   96.400298         0
1            2       3    male  46.012557  108.948810         1
2            3       3    male  34.738950   33.385867         0
3            4       3    male  24.185969   33.466690         0
4            5       1    male  38.858946   15.134000         1

Shape: (500, 6) (500 linhas × 6 colunas)

Tipos de dados:
PassengerId      int64
Pclass           int64
Sex             object
Age            float64
Fare           float64
Survived         int64
dtype: object

Estatísticas descritivas:
       PassengerId      Pclass         Age        Fare    Survived
count   500.000000  500.000000  500.000000  500.000000  500.000000
mean    250.500000    2.290000   31.160351   80.418234    0.398000
std     144.481833    0.814387   13.567708   40.607101    0.489976
min       1.000000    1.000000    1.000000   10.691597    0.000000
25%     125.750000    2.0

In [ ]:
# Verificar valores ausentes e qualidade dos dados
print("Valores nulos por coluna:")
nulos = df_titanic.isnull().sum()
percentual = (nulos / len(df_titanic) * 100).round(2)
qualidade = pd.DataFrame({'Nulos': nulos, 'Percentual (%)': percentual})
print(qualidade)

print(f"\nLinhas duplicadas: {df_titanic.duplicated().sum()}")

print("\nValores únicos por coluna:")
for col in df_titanic.columns:
    print(f"  {col}: {df_titanic[col].nunique()} valores únicos")

In [ ]:
# Limpeza e transformação de dados
df = df_titanic.copy()

# Preencher idade com a mediana (mais robusto que a média para dados com outliers)
df['Age'] = df['Age'].fillna(df['Age'].median())

# Mapear sexo para português
df['Sex'] = df['Sex'].map({'male': 'Masculino', 'female': 'Feminino'})

# Criar faixa etária com pd.cut
df['FaixaEtaria'] = pd.cut(
    df['Age'], 
    bins=[0, 12, 18, 35, 60, 100], 
    labels=['Criança', 'Adolescente', 'Jovem', 'Adulto', 'Idoso']
)

# Criar coluna de tarifa categorizada
df['TarifaCategoria'] = pd.qcut(
    df['Fare'], q=4, 
    labels=['Econômica', 'Básica', 'Intermediária', 'Premium']
)

print("Dataset após limpeza e feature engineering:")
print(df.head(10))
print(f"\nDistribuição por faixa etária:")
print(df['FaixaEtaria'].value_counts().sort_index())

In [ ]:
# Seleção e filtragem
# Selecionar colunas específicas
df_subset = df[['PassengerId', 'Pclass', 'Sex', 'Age', 'Survived']]
print("Subset de colunas:")
print(df_subset.head())

# Filtrar passageiros que sobreviveram
sobreviventes = df[df['Survived'] == 1]
print(f"\nTotal de sobreviventes: {len(sobreviventes)}")

# Múltiplas condições
mulheres_primeira_classe = df[(df['Sex'] == 'Feminino') & (df['Pclass'] == 1)]
print(f"\nMulheres na primeira classe: {len(mulheres_primeira_classe)}")
print(f"Taxa de sobrevivência: {mulheres_primeira_classe['Survived'].mean():.2%}")

In [ ]:
# Agrupamentos e agregações
print("Taxa de sobrevivência por classe:")
por_classe = df.groupby('Pclass')['Survived'].agg(['mean', 'sum', 'count'])
por_classe.columns = ['TaxaSobrevivencia', 'Sobreviventes', 'Total']
print(por_classe)

print("\nTaxa de sobrevivência por classe e sexo:")
por_classe_sexo = df.groupby(['Pclass', 'Sex'])['Survived'].agg(['mean', 'count'])
por_classe_sexo.columns = ['TaxaSobrevivencia', 'Total']
print(por_classe_sexo)

# Múltiplas agregações com named aggregation (pandas moderno)
print("\nEstatísticas de idade e tarifa por classe:")
stats_classe = df.groupby('Pclass').agg(
    idade_media=('Age', 'mean'),
    idade_mediana=('Age', 'median'),
    idade_std=('Age', 'std'),
    tarifa_media=('Fare', 'mean'),
    total_passageiros=('PassengerId', 'count')
)
print(stats_classe.round(2))

## 2.3 Análise do Dataset de Vendas

In [ ]:
# Carregar dataset de vendas
df_vendas = pd.read_csv("datasets/vendas.csv")
df_vendas['Data'] = pd.to_datetime(df_vendas['Data'])

print("Dataset de Vendas:")
print(df_vendas.head())
print(f"\nPeríodo: {df_vendas['Data'].min()} a {df_vendas['Data'].max()}")
print(f"Total de registros: {len(df_vendas)}")

In [ ]:
# Análise por região
print("Desempenho por Região:")
por_regiao = df_vendas.groupby('Regiao').agg({
    'Receita': ['sum', 'mean'],
    'Lucro': ['sum', 'mean'],
    'Qtd_Vendida': 'sum'
}).round(2)
print(por_regiao)

# Calcular margem de lucro
margem_por_regiao = (df_vendas.groupby('Regiao')['Lucro'].sum() / 
                     df_vendas.groupby('Regiao')['Receita'].sum() * 100)
print("\nMargem de Lucro por Região:")
print(margem_por_regiao.round(2))

In [ ]:
# Análise por produto
print("Top 5 Produtos por Receita:")
top_produtos = df_vendas.groupby('Produto').agg({
    'Receita': 'sum',
    'Lucro': 'sum',
    'Qtd_Vendida': 'sum'
}).sort_values('Receita', ascending=False)
print(top_produtos)

# Margem por produto
top_produtos['Margem_%'] = (top_produtos['Lucro'] / top_produtos['Receita'] * 100).round(2)
print("\nProdutos com margem:")
print(top_produtos)

In [ ]:
# Análise temporal
df_vendas['Ano'] = df_vendas['Data'].dt.year
df_vendas['Mes'] = df_vendas['Data'].dt.month
df_vendas['Trimestre'] = df_vendas['Data'].dt.quarter

print("Receita por Ano:")
por_ano = df_vendas.groupby('Ano')['Receita'].sum()
print(por_ano)

print("\nCrescimento ano a ano:")
crescimento = por_ano.pct_change() * 100
print(crescimento.round(2))

In [ ]:
# Desempenho por vendedor
print("Ranking de Vendedores:")
ranking_vendedores = df_vendas.groupby('Vendedor').agg({
    'Receita': 'sum',
    'Lucro': 'sum',
    'Qtd_Vendida': 'sum'
}).sort_values('Receita', ascending=False)
ranking_vendedores['Ticket_Medio'] = (ranking_vendedores['Receita'] / 
                                       ranking_vendedores['Qtd_Vendida'])
print(ranking_vendedores.round(2))

## 2.4 Operações Avançadas - Pivot, Merge e Window Functions

In [ ]:
# Pivot Table
pivot_vendas = pd.pivot_table(
    df_vendas,
    values='Receita',
    index='Regiao',
    columns='Produto',
    aggfunc='sum',
    fill_value=0
)

print("Pivot Table - Receita por Região e Produto:")
print(pivot_vendas.round(2))

In [ ]:
# Merge/Join — combinar DataFrames (similar a JOIN no SQL)
df_clientes = pd.DataFrame({
    'cliente_id': [1, 2, 3, 4, 5],
    'nome': ['Ana', 'Bruno', 'Carla', 'Diego', 'Eva'],
    'cidade': ['Fortaleza', 'Recife', 'Salvador', 'Fortaleza', 'Manaus']
})

df_pedidos = pd.DataFrame({
    'pedido_id': [101, 102, 103, 104, 105, 106],
    'cliente_id': [1, 2, 1, 3, 5, 2],
    'valor': [150.0, 230.0, 89.0, 410.0, 175.0, 320.0]
})

print("Clientes:")
print(df_clientes)
print("\nPedidos:")
print(df_pedidos)

# Inner join
inner = pd.merge(df_clientes, df_pedidos, on='cliente_id', how='inner')
print("\n--- INNER JOIN ---")
print(inner)

# Left join (inclui cliente sem pedido)
left = pd.merge(df_clientes, df_pedidos, on='cliente_id', how='left')
print("\n--- LEFT JOIN ---")
print(left)

# Agregação após merge
resumo = inner.groupby(['cliente_id', 'nome', 'cidade']).agg(
    total_pedidos=('pedido_id', 'count'),
    valor_total=('valor', 'sum'),
    ticket_medio=('valor', 'mean')
).reset_index().sort_values('valor_total', ascending=False)
print("\nResumo por cliente:")
print(resumo.round(2))

In [ ]:
# Window Functions — Rolling, Expanding, Shift
vendas_mensais = df_vendas.groupby(
    df_vendas['Data'].dt.to_period('M')
)['Receita'].sum().reset_index()
vendas_mensais['Data'] = vendas_mensais['Data'].dt.to_timestamp()
vendas_mensais.columns = ['Mes', 'Receita']

# Média móvel (3 meses)
vendas_mensais['MediaMovel_3m'] = vendas_mensais['Receita'].rolling(window=3).mean()

# Média acumulada (expanding)
vendas_mensais['MediaAcumulada'] = vendas_mensais['Receita'].expanding().mean()

# Variação percentual mês a mês
vendas_mensais['Variacao_%'] = vendas_mensais['Receita'].pct_change() * 100

# Receita do mês anterior (lag)
vendas_mensais['Receita_MesAnterior'] = vendas_mensais['Receita'].shift(1)

print("Vendas com Window Functions:")
print(vendas_mensais.round(2).to_string(index=False))

In [ ]:
# Aplicar função customizada
def classificar_receita(receita):
    if receita < 100000:
        return 'Baixa'
    elif receita < 300000:
        return 'Média'
    else:
        return 'Alta'

df_vendas['ClasseReceita'] = df_vendas['Receita'].apply(classificar_receita)

print("Distribuição por classe de receita:")
print(df_vendas['ClasseReceita'].value_counts())

In [ ]:
# Method Chaining — encadear operações para código mais limpo
resultado_chain = (
    df_vendas
    .query("Receita > 50000")
    .groupby('Regiao')
    .agg(
        receita_total=('Receita', 'sum'),
        lucro_total=('Lucro', 'sum'),
        num_vendas=('Receita', 'count')
    )
    .assign(margem_pct=lambda x: (x['lucro_total'] / x['receita_total'] * 100))
    .sort_values('receita_total', ascending=False)
    .round(2)
)

print("Análise com Method Chaining (receita > 50k):")
print(resultado_chain)

In [ ]:
# String operations
df_vendas['Regiao_Upper'] = df_vendas['Regiao'].str.upper()
df_vendas['Produto_Lower'] = df_vendas['Produto'].str.lower()
df_vendas['Tem_Norte'] = df_vendas['Regiao'].str.contains('Norte')

print("Registros da região Norte:")
print(df_vendas[df_vendas['Tem_Norte']].groupby('Regiao')['Receita'].sum())

<a id='modulo3'></a>
# 📊 Módulo 3 – Visualização e Análise Exploratória de Dados

A visualização é parte essencial da ciência de dados — transforma números em insights.  
Neste módulo utilizaremos **Matplotlib** e **Seaborn** para compreender padrões, distribuições e relações nos dados.

## 3.1 Matplotlib - Visualizações Fundamentais

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 11
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12

In [ ]:
# Histograma - Distribuição de idades no Titanic
plt.figure(figsize=(10, 6))
plt.hist(df['Age'], bins=30, alpha=0.7, color='skyblue', edgecolor='black')
plt.axvline(df['Age'].mean(), color='red', linestyle='--', linewidth=2, 
            label=f'Média: {df["Age"].mean():.1f}')
plt.axvline(df['Age'].median(), color='green', linestyle='--', linewidth=2, 
            label=f'Mediana: {df["Age"].median():.1f}')
plt.xlabel('Idade')
plt.ylabel('Frequência')
plt.title('Distribuição de Idades - Titanic', fontsize=14, fontweight='bold')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

In [ ]:
# Histogramas sobrepostos — comparar distribuições
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for survived, label, color in [(1, 'Sobreviveu', 'steelblue'), (0, 'Não sobreviveu', 'salmon')]:
    subset = df[df['Survived'] == survived]['Age']
    axes[0].hist(subset, bins=25, alpha=0.6, label=label, color=color, edgecolor='black')
axes[0].set_title('Distribuição de Idade por Sobrevivência', fontweight='bold')
axes[0].set_xlabel('Idade')
axes[0].set_ylabel('Frequência')
axes[0].legend()

for classe, color in [(1, '#2ecc71'), (2, '#3498db'), (3, '#e74c3c')]:
    subset = df[df['Pclass'] == classe]['Fare']
    axes[1].hist(subset, bins=25, alpha=0.5, label=f'{classe}ª Classe', color=color, edgecolor='black')
axes[1].set_title('Distribuição de Tarifa por Classe', fontweight='bold')
axes[1].set_xlabel('Tarifa (R$)')
axes[1].set_ylabel('Frequência')
axes[1].legend()

plt.tight_layout()
plt.show()

In [ ]:
# Gráfico de barras - Taxa de sobrevivência por classe
sobrevivencia_classe = df.groupby('Pclass')['Survived'].mean()

plt.figure(figsize=(10, 6))
bars = plt.bar(sobrevivencia_classe.index, sobrevivencia_classe.values, 
               color=['gold', 'silver', '#CD7F32'], edgecolor='black', alpha=0.8)

# Adicionar valores nas barras
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.1%}', ha='center', va='bottom', fontweight='bold')

plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Taxa de Sobrevivência', fontweight='bold')
plt.title('Taxa de Sobrevivência por Classe - Titanic', fontsize=14, fontweight='bold')
plt.xticks([1, 2, 3], ['1ª Classe', '2ª Classe', '3ª Classe'])
plt.ylim(0, 1)
plt.grid(True, alpha=0.3, axis='y')
plt.show()

In [ ]:
# Barras agrupadas — sobrevivência por classe e sexo
import numpy as np

taxa_por_grupo = df.groupby(['Pclass', 'Sex'])['Survived'].mean().unstack()

x = np.arange(len(taxa_por_grupo.index))
largura = 0.35

fig, ax = plt.subplots(figsize=(10, 6))
bars1 = ax.bar(x - largura/2, taxa_por_grupo['Feminino'], largura, 
               label='Feminino', color='#e74c3c', edgecolor='black', alpha=0.85)
bars2 = ax.bar(x + largura/2, taxa_por_grupo['Masculino'], largura, 
               label='Masculino', color='#3498db', edgecolor='black', alpha=0.85)

for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                f'{height:.0%}', ha='center', va='bottom', fontweight='bold', fontsize=11)

ax.set_xlabel('Classe', fontweight='bold')
ax.set_ylabel('Taxa de Sobrevivência', fontweight='bold')
ax.set_title('Taxa de Sobrevivência por Classe e Sexo', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(['1ª Classe', '2ª Classe', '3ª Classe'])
ax.set_ylim(0, 1.15)
ax.legend(title='Sexo')
ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

In [ ]:
# Subplots - Múltiplos gráficos
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Gráfico 1: Distribuição de idade
axes[0, 0].hist(df['Age'], bins=30, alpha=0.7, color='skyblue', edgecolor='black')
axes[0, 0].set_title('Distribuição de Idades', fontweight='bold')
axes[0, 0].set_xlabel('Idade')
axes[0, 0].set_ylabel('Frequência')

# Gráfico 2: Distribuição de tarifas
axes[0, 1].hist(df['Fare'], bins=30, alpha=0.7, color='lightcoral', edgecolor='black')
axes[0, 1].set_title('Distribuição de Tarifas', fontweight='bold')
axes[0, 1].set_xlabel('Tarifa')
axes[0, 1].set_ylabel('Frequência')

# Gráfico 3: Contagem por classe
df['Pclass'].value_counts().sort_index().plot(kind='bar', ax=axes[1, 0], 
                                               color='lightgreen', edgecolor='black')
axes[1, 0].set_title('Passageiros por Classe', fontweight='bold')
axes[1, 0].set_xlabel('Classe')
axes[1, 0].set_ylabel('Quantidade')
axes[1, 0].set_xticklabels(['1ª Classe', '2ª Classe', '3ª Classe'], rotation=0)

# Gráfico 4: Taxa de sobrevivência por sexo
df.groupby('Sex')['Survived'].mean().plot(kind='bar', ax=axes[1, 1], 
                                          color=['lightblue', 'pink'], edgecolor='black')
axes[1, 1].set_title('Taxa de Sobrevivência por Sexo', fontweight='bold')
axes[1, 1].set_xlabel('Sexo')
axes[1, 1].set_ylabel('Taxa de Sobrevivência')
axes[1, 1].set_xticklabels(['Feminino', 'Masculino'], rotation=0)

plt.tight_layout()
plt.show()

## 3.2 Seaborn - Visualizações Estatísticas

In [ ]:
# Box Plot - Distribuição de idade por classe e sobrevivência
plt.figure(figsize=(12, 6))
sns.boxplot(x='Pclass', y='Age', hue='Survived', data=df, palette='Set2')
plt.title('Distribuição de Idade por Classe e Sobrevivência', fontsize=14, fontweight='bold')
plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Idade', fontweight='bold')
plt.legend(title='Sobreviveu', labels=['Não', 'Sim'])
plt.show()

In [ ]:
# Violin Plot
plt.figure(figsize=(12, 6))
sns.violinplot(x='Pclass', y='Fare', hue='Sex', data=df, split=True, palette='muted')
plt.title('Distribuição de Tarifas por Classe e Sexo', fontsize=14, fontweight='bold')
plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Tarifa', fontweight='bold')
plt.legend(title='Sexo')
plt.show()

In [ ]:
# Count Plot
plt.figure(figsize=(12, 6))
sns.countplot(x='Pclass', hue='Survived', data=df, palette='viridis')
plt.title('Contagem de Passageiros por Classe e Sobrevivência', fontsize=14, fontweight='bold')
plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Contagem', fontweight='bold')
plt.legend(title='Sobreviveu', labels=['Não', 'Sim'])
plt.show()

In [ ]:
# Heatmap de correlação
plt.figure(figsize=(10, 8))
correlacao = df[['Pclass', 'Age', 'Fare', 'Survived']].corr()
sns.heatmap(correlacao, annot=True, cmap='coolwarm', center=0, 
            square=True, linewidths=1, cbar_kws={"shrink": 0.8})
plt.title('Matriz de Correlação - Titanic', fontsize=14, fontweight='bold')
plt.show()

In [ ]:
# Pair Plot — visão geral das relações entre variáveis numéricas
g = sns.pairplot(
    df[['Age', 'Fare', 'Pclass', 'Survived']],
    hue='Survived',
    palette={0: '#e74c3c', 1: '#2ecc71'},
    diag_kind='kde',
    plot_kws={'alpha': 0.5, 's': 30},
    height=2.5
)
g.figure.suptitle('Pair Plot — Variáveis Numéricas do Titanic', y=1.02, fontsize=14, fontweight='bold')
plt.show()

In [ ]:
# KDE (Kernel Density Estimation) — distribuições suavizadas
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for survived, label, color in [(0, 'Não Sobreviveu', '#e74c3c'), (1, 'Sobreviveu', '#2ecc71')]:
    subset = df[df['Survived'] == survived]['Age']
    sns.kdeplot(subset, ax=axes[0], label=label, color=color, linewidth=2.5, fill=True, alpha=0.3)
axes[0].set_title('Densidade de Idade por Sobrevivência', fontweight='bold')
axes[0].set_xlabel('Idade')
axes[0].legend()

for classe, color in [(1, '#2ecc71'), (2, '#3498db'), (3, '#e74c3c')]:
    subset = df[df['Pclass'] == classe]['Fare']
    sns.kdeplot(subset, ax=axes[1], label=f'{classe}ª Classe', color=color, linewidth=2.5, fill=True, alpha=0.2)
axes[1].set_title('Densidade de Tarifa por Classe', fontweight='bold')
axes[1].set_xlabel('Tarifa')
axes[1].legend()

plt.tight_layout()
plt.show()

In [ ]:
# Scatter Plot com linha de regressão (lmplot)
g = sns.lmplot(
    data=df, x='Age', y='Fare', hue='Survived',
    palette={0: '#e74c3c', 1: '#2ecc71'},
    height=6, aspect=1.5,
    scatter_kws={'alpha': 0.4, 's': 40},
    line_kws={'linewidth': 2}
)
g.set_axis_labels('Idade', 'Tarifa', fontweight='bold')
g.figure.suptitle('Relação Idade × Tarifa por Sobrevivência', y=1.02, fontsize=14, fontweight='bold')
plt.show()

In [ ]:
# FacetGrid — dividir gráfico por categorias
g = sns.FacetGrid(df, col='Pclass', row='Sex', hue='Survived',
                  palette={0: '#e74c3c', 1: '#2ecc71'}, 
                  height=3.5, aspect=1.3, margin_titles=True)
g.map(plt.hist, 'Age', alpha=0.6, bins=20, edgecolor='black')
g.add_legend(title='Sobreviveu', labels=['Não', 'Sim'])
g.figure.suptitle('Distribuição de Idade por Classe, Sexo e Sobrevivência', 
                  y=1.02, fontsize=14, fontweight='bold')
plt.show()

## 3.3 Visualizações com Dados de Vendas

In [ ]:
# Evolução temporal de vendas
vendas_mensais = df_vendas.groupby(df_vendas['Data'].dt.to_period('M'))['Receita'].sum()
vendas_mensais.index = vendas_mensais.index.to_timestamp()

plt.figure(figsize=(15, 6))
plt.plot(vendas_mensais.index, vendas_mensais.values, marker='o', linewidth=2)
plt.fill_between(vendas_mensais.index, vendas_mensais.values, alpha=0.3)
plt.title('Evolução Mensal de Receita', fontsize=14, fontweight='bold')
plt.xlabel('Data', fontweight='bold')
plt.ylabel('Receita', fontweight='bold')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# Evolução temporal com média móvel
vendas_plot = df_vendas.groupby(df_vendas['Data'].dt.to_period('M')).agg(
    receita=('Receita', 'sum'),
    lucro=('Lucro', 'sum')
).reset_index()
vendas_plot['Data'] = vendas_plot['Data'].dt.to_timestamp()
vendas_plot['mm3_receita'] = vendas_plot['receita'].rolling(3).mean()
vendas_plot['mm3_lucro'] = vendas_plot['lucro'].rolling(3).mean()

fig, ax = plt.subplots(figsize=(15, 6))
ax.plot(vendas_plot['Data'], vendas_plot['receita'], 'o-', color='steelblue', 
        alpha=0.4, linewidth=1, label='Receita mensal')
ax.plot(vendas_plot['Data'], vendas_plot['mm3_receita'], '-', color='steelblue', 
        linewidth=2.5, label='Média móvel 3m (Receita)')
ax.plot(vendas_plot['Data'], vendas_plot['lucro'], 's-', color='#2ecc71', 
        alpha=0.4, linewidth=1, label='Lucro mensal')
ax.plot(vendas_plot['Data'], vendas_plot['mm3_lucro'], '-', color='#2ecc71', 
        linewidth=2.5, label='Média móvel 3m (Lucro)')

ax.set_title('Evolução de Receita e Lucro com Média Móvel', fontsize=14, fontweight='bold')
ax.set_xlabel('Data', fontweight='bold')
ax.set_ylabel('Valor (R$)', fontweight='bold')
ax.legend(loc='upper left')
ax.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# Gráfico de barras horizontal - Receita por região
receita_regiao = df_vendas.groupby('Regiao')['Receita'].sum().sort_values()

plt.figure(figsize=(10, 6))
bars = plt.barh(receita_regiao.index, receita_regiao.values, 
                color=sns.color_palette('husl', len(receita_regiao)))

# Adicionar valores
for i, (idx, val) in enumerate(receita_regiao.items()):
    plt.text(val, i, f' R$ {val:,.0f}', va='center', fontweight='bold')

plt.title('Receita Total por Região', fontsize=14, fontweight='bold')
plt.xlabel('Receita (R$)', fontweight='bold')
plt.ylabel('Região', fontweight='bold')
plt.grid(True, alpha=0.3, axis='x')
plt.tight_layout()
plt.show()

In [ ]:
# Gráfico de pizza - Participação por produto
vendas_produto = df_vendas.groupby('Produto')['Receita'].sum()

plt.figure(figsize=(10, 8))
colors = sns.color_palette('pastel')
plt.pie(vendas_produto.values, labels=vendas_produto.index, autopct='%1.1f%%',
        startangle=90, colors=colors, wedgeprops={'edgecolor': 'black'})
plt.title('Participação de Cada Produto na Receita Total', fontsize=14, fontweight='bold')
plt.axis('equal')
plt.show()

In [ ]:
# Heatmap - Receita por região e produto
pivot_reg_prod = pd.pivot_table(
    df_vendas, 
    values='Receita', 
    index='Regiao', 
    columns='Produto', 
    aggfunc='sum'
)

plt.figure(figsize=(12, 6))
sns.heatmap(pivot_reg_prod, annot=True, fmt='.0f', cmap='YlOrRd', 
            linewidths=0.5, cbar_kws={'label': 'Receita'})
plt.title('Receita por Região e Produto', fontsize=14, fontweight='bold')
plt.xlabel('Produto', fontweight='bold')
plt.ylabel('Região', fontweight='bold')
plt.tight_layout()
plt.show()

In [ ]:
# Barras empilhadas — composição da receita por região e produto
pivot_pct = pd.pivot_table(
    df_vendas, values='Receita', index='Regiao', 
    columns='Produto', aggfunc='sum', fill_value=0
)
pivot_pct_norm = pivot_pct.div(pivot_pct.sum(axis=1), axis=0) * 100

pivot_pct_norm.plot(kind='barh', stacked=True, figsize=(12, 6), 
                     colormap='Set2', edgecolor='black', alpha=0.85)
plt.title('Composição da Receita por Região (% por Produto)', fontsize=14, fontweight='bold')
plt.xlabel('Participação (%)', fontweight='bold')
plt.ylabel('Região', fontweight='bold')
plt.legend(title='Produto', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

## 3.4 Análise Exploratória do Dataset de COVID

In [ ]:
# Carregar e preparar dados de COVID
df_covid = pd.read_csv("datasets/covid.csv")
df_covid['Data'] = pd.to_datetime(df_covid['Data'])

print("Dataset COVID-19:")
print(df_covid.head())
print(f"\nPeríodo: {df_covid['Data'].min()} a {df_covid['Data'].max()}")

In [ ]:
# Evolução de casos por região
fig, axes = plt.subplots(2, 1, figsize=(15, 10))

# Casos ao longo do tempo
for regiao in df_covid['Regiao'].unique():
    dados_regiao = df_covid[df_covid['Regiao'] == regiao]
    axes[0].plot(dados_regiao['Data'], dados_regiao['Casos'], 
                 marker='o', label=regiao, linewidth=2)

axes[0].set_title('Evolução de Casos de COVID-19 por Região', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Data', fontweight='bold')
axes[0].set_ylabel('Casos', fontweight='bold')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Óbitos ao longo do tempo
for regiao in df_covid['Regiao'].unique():
    dados_regiao = df_covid[df_covid['Regiao'] == regiao]
    axes[1].plot(dados_regiao['Data'], dados_regiao['Obitos'], 
                 marker='s', label=regiao, linewidth=2)

axes[1].set_title('Evolução de Óbitos por COVID-19 por Região', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Data', fontweight='bold')
axes[1].set_ylabel('Óbitos', fontweight='bold')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

In [ ]:
# Totais por região
totais_covid = df_covid.groupby('Regiao').agg({
    'Casos': 'sum',
    'Obitos': 'sum',
    'Vacinados': 'sum'
})

totais_covid['Taxa_Mortalidade'] = (totais_covid['Obitos'] / totais_covid['Casos'] * 100)
totais_covid['Taxa_Vacinacao'] = (totais_covid['Vacinados'] / totais_covid['Casos'] * 100)

print("Estatísticas Totais de COVID-19 por Região:")
print(totais_covid.round(2))

In [ ]:
# Dashboard comparativo — COVID-19
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

totais_covid['Casos'].sort_values().plot(
    kind='barh', ax=axes[0, 0], color='steelblue', edgecolor='black')
axes[0, 0].set_title('Total de Casos por Região', fontweight='bold')
axes[0, 0].set_xlabel('Casos')

totais_covid['Taxa_Mortalidade'].sort_values().plot(
    kind='barh', ax=axes[0, 1], color='crimson', edgecolor='black')
axes[0, 1].set_title('Taxa de Mortalidade (%)', fontweight='bold')
axes[0, 1].set_xlabel('Taxa (%)')

totais_covid['Vacinados'].sort_values().plot(
    kind='barh', ax=axes[1, 0], color='#2ecc71', edgecolor='black')
axes[1, 0].set_title('Total de Vacinados por Região', fontweight='bold')
axes[1, 0].set_xlabel('Vacinados')

axes[1, 1].scatter(totais_covid['Casos'], totais_covid['Obitos'], 
                    s=totais_covid['Vacinados']/500, alpha=0.7, 
                    color='purple', edgecolors='black')
for idx, row in totais_covid.iterrows():
    axes[1, 1].annotate(idx, (row['Casos'], row['Obitos']), 
                         fontsize=9, ha='center', va='bottom')
axes[1, 1].set_title('Casos vs Óbitos (tamanho = vacinados)', fontweight='bold')
axes[1, 1].set_xlabel('Casos')
axes[1, 1].set_ylabel('Óbitos')

plt.suptitle('Dashboard COVID-19 por Região', fontsize=16, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()

## 3.5 Detecção Visual de Outliers

In [ ]:
# Detecção de outliers com IQR e visualização
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for i, (col, titulo) in enumerate([('Age', 'Idade'), ('Fare', 'Tarifa')]):
    dados_col = df[col].dropna()
    Q1 = dados_col.quantile(0.25)
    Q3 = dados_col.quantile(0.75)
    IQR = Q3 - Q1
    limite_inf = Q1 - 1.5 * IQR
    limite_sup = Q3 + 1.5 * IQR
    outliers = dados_col[(dados_col < limite_inf) | (dados_col > limite_sup)]
    
    sns.boxplot(y=dados_col, ax=axes[i], color='lightblue', 
                flierprops={'markerfacecolor': 'red', 'markersize': 8})
    axes[i].axhline(limite_inf, color='orange', linestyle='--', alpha=0.7, label=f'Lim. Inf: {limite_inf:.1f}')
    axes[i].axhline(limite_sup, color='orange', linestyle='--', alpha=0.7, label=f'Lim. Sup: {limite_sup:.1f}')
    axes[i].set_title(f'{titulo}\n({len(outliers)} outliers de {len(dados_col)})', fontweight='bold')
    axes[i].legend(fontsize=9)

sns.boxplot(x='Pclass', y='Fare', data=df, ax=axes[2], palette='Set2')
axes[2].set_title('Tarifa por Classe\n(comparação de outliers)', fontweight='bold')
axes[2].set_xlabel('Classe')
axes[2].set_ylabel('Tarifa')

plt.tight_layout()
plt.show()

## 3.6 Resumo da Análise Exploratória

In [ ]:
# Função de resumo EDA automatizado
def resumo_eda(df, nome_dataset="Dataset"):
    print(f"{'='*60}")
    print(f"  RESUMO EDA — {nome_dataset}")
    print(f"{'='*60}")
    print(f"\n\U0001f4d0 Dimensões: {df.shape[0]} linhas × {df.shape[1]} colunas")
    
    print(f"\n\U0001f4ca Tipos de dados:")
    for dtype, count in df.dtypes.value_counts().items():
        print(f"   {dtype}: {count} coluna(s)")
    
    nulos_total = df.isnull().sum().sum()
    pct_nulos = (nulos_total / (df.shape[0] * df.shape[1])) * 100
    print(f"\n\U0001f50d Valores nulos: {nulos_total} ({pct_nulos:.2f}%)")
    print(f"\U0001f4cb Duplicatas: {df.duplicated().sum()}")
    
    mem = df.memory_usage(deep=True).sum() / 1024
    print(f"\U0001f4be Memória: {mem:.1f} KB")
    
    numericas = df.select_dtypes(include='number')
    if not numericas.empty:
        print(f"\n\U0001f4c8 Colunas numéricas ({len(numericas.columns)}):")
        for col in numericas.columns:
            skew = numericas[col].skew()
            sinal_skew = "\u2192 simétrica" if abs(skew) < 0.5 else ("\u2192 assimetria positiva" if skew > 0 else "\u2192 assimetria negativa")
            print(f"   {col}: média={numericas[col].mean():.2f}, std={numericas[col].std():.2f}, skew={skew:.2f} {sinal_skew}")
    
    categoricas = df.select_dtypes(include='object')
    if not categoricas.empty:
        print(f"\n\U0001f3f7 Colunas categóricas ({len(categoricas.columns)}):")
        for col in categoricas.columns:
            print(f"   {col}: {categoricas[col].nunique()} categorias \u2014 top: '{categoricas[col].mode().iloc[0]}'")

resumo_eda(df, "Titanic")
print()
resumo_eda(df_vendas, "Vendas")

## \u2705 Conclusão

Este notebook forneceu uma base técnica sólida e abrangente em programação e análise de dados com Python, cobrindo:

- **Fundamentos de Python**: Tipos, conversões, strings, estruturas de dados (listas, dicts, tuplas, sets), controle de fluxo, compreensões, programação funcional, funções avançadas (decorators, *args/**kwargs), tratamento de erros, generators
- **NumPy**: Arrays, operações vetorizadas, broadcasting, reshape, álgebra linear, estatísticas
- **Pandas**: Series, DataFrames, limpeza de dados, feature engineering, agrupamentos, merge/join, window functions, method chaining
- **Visualização**: Matplotlib (histogramas, barras, subplots), Seaborn (boxplot, violin, heatmap, pairplot, KDE, FacetGrid, lmplot), detecção de outliers, dashboards, funções de resumo EDA

### Próximos Passos

1. Explorar análises estatísticas e testes de hipóteses (Módulo 4)
2. Introdução a Machine Learning com scikit-learn (Módulo 4)
3. Desenvolver o projeto final integrado (Módulo 5)

### Recursos Adicionais

- Documentação Pandas: [pandas.pydata.org](https://pandas.pydata.org)
- Documentação NumPy: [numpy.org](https://numpy.org)
- Matplotlib: [matplotlib.org](https://matplotlib.org)
- Seaborn: [seaborn.pydata.org](https://seaborn.pydata.org)
- Python Data Science Handbook: [jakevdp.github.io](https://jakevdp.github.io/PythonDataScienceHandbook/)
- Kaggle: [kaggle.com](https://kaggle.com) — datasets e competições

**Bons estudos e boa análise de dados!**