# 📘 Programação para Ciência de Dados – MBA Ciência de Dados, Universidade de Fortaleza

**Instrutor:** Cássio Pinheiro  
**Carga horária:** 28h  
**Formato:** Intensivo 
**Linguagem:** Python  
**Ambiente:** Jupyter Notebook / Google Colab

Este notebook integra os cinco módulos da disciplina **Programação para Ciência de Dados**, combinando teoria técnica, exemplos práticos detalhados e desafios aplicados usando datasets reais.

---

## 📑 Índice

1. [Módulo 1 - Fundamentos de Programação com Python](#modulo1)
2. [Módulo 2 - Manipulação Avançada com Pandas e NumPy](#modulo2)
3. [Módulo 3 - Visualização e Análise Exploratória de Dados](#modulo3)
4. [Módulo 4 - Análise Estatística e Machine Learning](#modulo4)
5. [Módulo 5 - Projeto Final Integrado](#modulo5)

<a id='modulo1'></a>
# 🧩 Módulo 1 – Fundamentos de Programação com Python

Neste módulo, abordamos a base da linguagem Python aplicada à ciência de dados.  
Exploramos tipos de dados, estruturas de controle, funções, compreensão de listas, e boas práticas.

## 1.1 Tipos de Dados e Operações Básicas

In [6]:
print("MOstre alguma coisa")

MOstre alguma coisa


In [8]:
# Tipos de dados e operações
x, y = 10, 3

print(f"Soma: {x + y}")
print(f"Subtração: {x - y}")
print(f"Multiplicação: {x * y}")
print(f"Divisão: {x / y:.2f}")
print(f"Divisão inteira: {x // y}")
print(f"Resto: {x % y}")
print(f"Potência: {x ** y}")


Soma: 13
Subtração: 7
Multiplicação: 30
Divisão: 3.33
Divisão inteira: 3
Resto: 1
Potência: 1000


## 1.2 Estruturas de Dados Fundamentais

In [5]:
# Listas
numeros = [1, 2, 3, 4, 5]
print("Lista original:", numeros)
print("Primeiro elemento:", numeros[0])
print("Últimos dois:", numeros[-2:])
print("Slice [1:4]:", numeros[1:4])

# Operações com listas
numeros.append(6)
numeros.extend([7, 8])
numeros.insert(0, 0)
print("Após operações:", numeros)

Lista original: [1, 2, 3, 4, 5]
Primeiro elemento: 1
Últimos dois: [4, 5]
Slice [1:4]: [2, 3, 4]
Após operações: [0, 1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# Dicionários
aluno = {
    'nome': 'Ana Silva',
    'idade': 28,
    'curso': 'MBA Ciência de Dados',
    'notas': [8.5, 9.0, 7.5, 8.0]
}

print(f"Nome: {aluno['nome']}")
print(f"Média: {sum(aluno['notas']) / len(aluno['notas']):.2f}")

# Iteração
for chave, valor in aluno.items():
    print(f"{chave}: {valor}")

Nome: Ana Silva
Média: 8.25
nome: Ana Silva
idade: 28
curso: MBA Ciência de Dados
notas: [8.5, 9.0, 7.5, 8.0]


In [7]:
# Tuplas e Sets
coordenadas = (10.5, 20.3)
x, y = coordenadas  # Unpacking
print(f"X: {x}, Y: {y}")

# Sets - operações de conjunto
set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}

print(f"União: {set_a | set_b}")
print(f"Interseção: {set_a & set_b}")
print(f"Diferença: {set_b - set_a}")
print(f"Diferença simétrica: {set_a ^ set_b}")

X: 10.5, Y: 20.3
União: {1, 2, 3, 4, 5, 6, 7, 8}
Interseção: {4, 5}
Diferença: {8, 6, 7}
Diferença simétrica: {1, 2, 3, 6, 7, 8}


## 1.3 Estruturas de Controle

In [9]:
# Estruturas condicionais e laços
valores = [10, 15, 20, 25, 30]

for v in valores:
    if v % 2 == 0:
        print(f"{v} é par")
    else:
        print(f"{v} é ímpar")

# While loop
contador = 0
soma = 0
while contador < 5:
    soma += contador
    contador += 1
print(f"Soma de 0 a 4: {soma}")

10 é par
15 é ímpar
20 é par
25 é ímpar
30 é par
Soma de 0 a 4: 10


## 1.4 Compreensões e Programação Funcional

In [1]:
# List comprehension
quadrados = [x**2 for x in range(1, 11)]
print("Quadrados:", quadrados)

# Com condição
pares = [x for x in quadrados if x % 2 == 0]
print("Apenas pares:", pares)

# Dict comprehension
quadrados_dict = {x: x**2 for x in range(1, 6)}
print("Dicionário de quadrados:", quadrados_dict)

# Set comprehension
vogais = {letra.lower() for palavra in ['Python', 'Data', 'Science'] 
          for letra in palavra if letra.lower() in 'aeiou'}
print("Vogais únicas:", vogais)

Quadrados: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
Apenas pares: [4, 16, 36, 64, 100]
Dicionário de quadrados: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
Vogais únicas: {'a', 'o', 'e', 'i'}


In [2]:
# Funções lambda e map/filter/reduce
dobro = lambda x: x * 2
numeros_dobrados = list(map(dobro, [1, 2, 3, 4]))
print("Dobrados:", numeros_dobrados)

# Filter
pares_filter = list(filter(lambda x: x % 2 == 0, range(10)))
print("Pares com filter:", pares_filter)

# Reduce
from functools import reduce
produto = reduce(lambda x, y: x * y, [1, 2, 3, 4, 5])
print(f"Produto de 1 a 5: {produto}")

Dobrados: [2, 4, 6, 8]
Pares com filter: [0, 2, 4, 6, 8]
Produto de 1 a 5: 120


## 1.5 Funções Avançadas

In [3]:
# Função com argumentos padrão e documentação
def calcular_estatisticas(dados, incluir_media=True, incluir_mediana=False):
    """
    Calcula estatísticas básicas de uma lista de números.
    
    Args:
        dados (list): Lista de números
        incluir_media (bool): Se True, calcula a média
        incluir_mediana (bool): Se True, calcula a mediana
    
    Returns:
        dict: Dicionário com as estatísticas calculadas
    """
    resultado = {
        'minimo': min(dados),
        'maximo': max(dados),
        'quantidade': len(dados)
    }
    
    if incluir_media:
        resultado['media'] = sum(dados) / len(dados)
    
    if incluir_mediana:
        dados_ordenados = sorted(dados)
        n = len(dados_ordenados)
        if n % 2 == 0:
            resultado['mediana'] = (dados_ordenados[n//2-1] + dados_ordenados[n//2]) / 2
        else:
            resultado['mediana'] = dados_ordenados[n//2]
    
    return resultado

# Teste
dados = [10, 20, 30, 40, 50]
stats = calcular_estatisticas(dados, incluir_mediana=True)
print(stats)

{'minimo': 10, 'maximo': 50, 'quantidade': 5, 'media': 30.0, 'mediana': 30}


## 1.6 Manipulação de Arquivos

In [4]:
# Escrita de arquivo
with open("exemplo.txt", "w", encoding='utf-8') as f:
    f.write("Disciplina: Programação para Ciência de Dados\n")
    f.write("Instrutor: Cássio Pinheiro\n")
    f.write("Universidade de Fortaleza\n")

# Leitura de arquivo
with open("exemplo.txt", "r", encoding='utf-8') as f:
    conteudo = f.read()
    print(conteudo)

# Leitura linha por linha
with open("exemplo.txt", "r", encoding='utf-8') as f:
    for i, linha in enumerate(f, 1):
        print(f"Linha {i}: {linha.strip()}")

Disciplina: Programação para Ciência de Dados
Instrutor: Cássio Pinheiro
Universidade de Fortaleza

Linha 1: Disciplina: Programação para Ciência de Dados
Linha 2: Instrutor: Cássio Pinheiro
Linha 3: Universidade de Fortaleza


<a id='modulo2'></a>
# 🧮 Módulo 2 – Manipulação Avançada com Pandas e NumPy

Introdução à manipulação de dados estruturados com as bibliotecas `pandas` e `numpy`.  
Inclui leitura, limpeza, transformação, agregações e joins.

## 2.1 NumPy - Fundamentos

In [6]:
import numpy as np
# Criação de arrays
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
identidade = np.eye(3)
aleatorio = np.random.rand(3, 3)

print("Array 1D:", arr1d)
print("\nArray 2D:\n", arr2d)
print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)

print("\nIdentidade:\n", identidade)
print("\nAleatório:\n", aleatorio)

Array 1D: [1 2 3 4 5]

Array 2D:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Identidade:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Aleatório:
 [[0.40191293 0.98268488 0.18355873]
 [0.3292981  0.15942665 0.13253095]
 [0.13540146 0.24284479 0.01207965]]


In [ ]:
# Operações vetorizadas (muito mais rápidas que loops)
arr = np.array([1, 2, 3, 4, 5])

print("Original:", arr)
print("Multiplicado por 2:", arr * 2)
print("Ao quadrado:", arr ** 2)
print("Mais 10:", arr + 10)

# Operações entre arrays
arr2 = np.array([10, 20, 30, 40, 50])
print("Soma do elemento a elemento:", arr + arr2)
print("Produto elemento a elemento:", arr * arr2)

Original: [1 2 3 4 5]
Multiplicado por 2: [ 2  4  6  8 10]
Ao quadrado: [ 1  4  9 16 25]
Mais 10: [11 12 13 14 15]
Soma de arrays: [11 22 33 44 55]
Produto elemento a elemento: [ 10  40  90 160 250]


In [7]:
# Indexação e fatiamento
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Indexação booleana
maiores_que_5 = arr[arr > 5]
print("Maiores que 5:", maiores_que_5)

pares = arr[arr % 2 == 0]
print("Pares:", pares)

# Fancy indexing
indices = [0, 2, 4, 6]
elementos = arr[indices]
print("Elementos nos índices [0,2,4,6]:", elementos)

Maiores que 5: [ 6  7  8  9 10]
Pares: [ 2  4  6  8 10]
Elementos nos índices [0,2,4,6]: [1 3 5 7]


In [8]:
# Operações estatísticas
np.random.seed(42)
dados = np.random.randn(1000)

print(f"Média: {np.mean(dados):.4f}")
print(f"Mediana: {np.median(dados):.4f}")
print(f"Desvio padrão: {np.std(dados):.4f}")
print(f"Variância: {np.var(dados):.4f}")
print(f"Mínimo: {np.min(dados):.4f}")
print(f"Máximo: {np.max(dados):.4f}")
print(f"Percentil 25: {np.percentile(dados, 25):.4f}")
print(f"Percentil 75: {np.percentile(dados, 75):.4f}")

Média: 0.0193
Mediana: 0.0253
Desvio padrão: 0.9787
Variância: 0.9579
Mínimo: -3.2413
Máximo: 3.8527
Percentil 25: -0.6476
Percentil 75: 0.6479


In [ ]:
# Álgebra linear
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# Multiplicação de matrizes
produto = np.dot(A, B)
print("\nA × B:\n", produto)

# Determinante
det_A = np.linalg.det(A)
print(f"\nDeterminante de A: {det_A}")

# Inversa
inv_A = np.linalg.inv(A)
print("\nInversa de A:\n", inv_A)

# Autovalores e autovetores
autovalores, autovetores = np.linalg.eig(A)
print("\nAutovalores:", autovalores)
print("\nAutovetores:\n", autovetores)

## 2.2 Pandas - DataFrames e Series

Vamos trabalhar com os datasets reais disponíveis.

In [9]:
import pandas as pd

# Leitura do dataset Titanic
df_titanic = pd.read_csv("datasets/titanic.csv")

print("Primeiras linhas:")
print(df_titanic.head())

print("\nInformações do dataset:")
print(df_titanic.info())

print("\nEstatísticas descritivas:")
print(df_titanic.describe())

Primeiras linhas:
   PassengerId  Pclass     Sex        Age        Fare  Survived
0            1       2  female   9.299793   96.400298         0
1            2       3    male  46.012557  108.948810         1
2            3       3    male  34.738950   33.385867         0
3            4       3    male  24.185969   33.466690         0
4            5       1    male  38.858946   15.134000         1

Informações do dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  500 non-null    int64  
 1   Pclass       500 non-null    int64  
 2   Sex          500 non-null    object 
 3   Age          500 non-null    float64
 4   Fare         500 non-null    float64
 5   Survived     500 non-null    int64  
dtypes: float64(2), int64(3), object(1)
memory usage: 23.6+ KB
None

Estatísticas descritivas:
       PassengerId      Pclass        

In [10]:
# Verificar valores ausentes
print("Valores nulos por coluna:")
print(df_titanic.isnull().sum())

print("\nPercentual de valores nulos:")
print((df_titanic.isnull().sum() / len(df_titanic) * 100).round(2))

Valores nulos por coluna:
PassengerId    0
Pclass         0
Sex            0
Age            0
Fare           0
Survived       0
dtype: int64

Percentual de valores nulos:
PassengerId    0.0
Pclass         0.0
Sex            0.0
Age            0.0
Fare           0.0
Survived       0.0
dtype: float64


In [11]:
# Limpeza de dados
df = df_titanic.copy()

# Preencher idade com a média
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Mapear sexo para português
df['Sex'] = df['Sex'].map({'male': 'Masculino', 'female': 'Feminino'})

# Criar faixa etária
df['FaixaEtaria'] = pd.cut(df['Age'], bins=[0, 18, 35, 60, 100], 
                            labels=['Criança/Adolescente', 'Jovem', 'Adulto', 'Idoso'])

print("Dataset após limpeza:")
print(df.head())

Dataset após limpeza:
   PassengerId  Pclass        Sex        Age        Fare  Survived  \
0            1       2   Feminino   9.299793   96.400298         0   
1            2       3  Masculino  46.012557  108.948810         1   
2            3       3  Masculino  34.738950   33.385867         0   
3            4       3  Masculino  24.185969   33.466690         0   
4            5       1  Masculino  38.858946   15.134000         1   

           FaixaEtaria  
0  Criança/Adolescente  
1               Adulto  
2                Jovem  
3                Jovem  
4               Adulto  


/var/folders/vb/vy336l7j73gcpyl6p4b48pg40000gn/T/ipykernel_4436/498840414.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)


In [ ]:
# Seleção e filtragem
# Selecionar colunas específicas
df_subset = df[['PassengerId', 'Pclass', 'Sex', 'Age', 'Survived']]
print("Subset de colunas:")
print(df_subset.head())

# Filtrar passageiros que sobreviveram
sobreviventes = df[df['Survived'] == 1]
print(f"\nTotal de sobreviventes: {len(sobreviventes)}")

# Múltiplas condições
mulheres_primeira_classe = df[(df['Sex'] == 'Feminino') & (df['Pclass'] == 1)]
print(f"\nMulheres na primeira classe: {len(mulheres_primeira_classe)}")
print(f"Taxa de sobrevivência: {mulheres_primeira_classe['Survived'].mean():.2%}")

In [ ]:
# Agrupamentos e agregações
print("Taxa de sobrevivência por classe:")
por_classe = df.groupby('Pclass')['Survived'].agg(['mean', 'count'])
por_classe.columns = ['TaxaSobrevivencia', 'Total']
print(por_classe)

print("\nTaxa de sobrevivência por classe e sexo:")
por_classe_sexo = df.groupby(['Pclass', 'Sex'])['Survived'].agg(['mean', 'count'])
por_classe_sexo.columns = ['TaxaSobrevivencia', 'Total']
print(por_classe_sexo)

# Múltiplas agregações
print("\nEstatísticas de idade por classe:")
stats_idade = df.groupby('Pclass')['Age'].agg(['mean', 'median', 'min', 'max', 'std'])
print(stats_idade.round(2))

## 2.3 Análise do Dataset de Vendas

In [ ]:
# Carregar dataset de vendas
df_vendas = pd.read_csv("datasets/vendas.csv")
df_vendas['Data'] = pd.to_datetime(df_vendas['Data'])

print("Dataset de Vendas:")
print(df_vendas.head())
print(f"\nPeríodo: {df_vendas['Data'].min()} a {df_vendas['Data'].max()}")
print(f"Total de registros: {len(df_vendas)}")

In [ ]:
# Análise por região
print("Desempenho por Região:")
por_regiao = df_vendas.groupby('Regiao').agg({
    'Receita': ['sum', 'mean'],
    'Lucro': ['sum', 'mean'],
    'Qtd_Vendida': 'sum'
}).round(2)
print(por_regiao)

# Calcular margem de lucro
margem_por_regiao = (df_vendas.groupby('Regiao')['Lucro'].sum() / 
                     df_vendas.groupby('Regiao')['Receita'].sum() * 100)
print("\nMargem de Lucro por Região:")
print(margem_por_regiao.round(2))

In [ ]:
# Análise por produto
print("Top 5 Produtos por Receita:")
top_produtos = df_vendas.groupby('Produto').agg({
    'Receita': 'sum',
    'Lucro': 'sum',
    'Qtd_Vendida': 'sum'
}).sort_values('Receita', ascending=False)
print(top_produtos)

# Margem por produto
top_produtos['Margem_%'] = (top_produtos['Lucro'] / top_produtos['Receita'] * 100).round(2)
print("\nProdutos com margem:")
print(top_produtos)

In [ ]:
# Análise temporal
df_vendas['Ano'] = df_vendas['Data'].dt.year
df_vendas['Mes'] = df_vendas['Data'].dt.month
df_vendas['Trimestre'] = df_vendas['Data'].dt.quarter

print("Receita por Ano:")
por_ano = df_vendas.groupby('Ano')['Receita'].sum()
print(por_ano)

print("\nCrescimento ano a ano:")
crescimento = por_ano.pct_change() * 100
print(crescimento.round(2))

In [ ]:
# Desempenho por vendedor
print("Ranking de Vendedores:")
ranking_vendedores = df_vendas.groupby('Vendedor').agg({
    'Receita': 'sum',
    'Lucro': 'sum',
    'Qtd_Vendida': 'sum'
}).sort_values('Receita', ascending=False)
ranking_vendedores['Ticket_Medio'] = (ranking_vendedores['Receita'] / 
                                       ranking_vendedores['Qtd_Vendida'])
print(ranking_vendedores.round(2))

## 2.4 Operações Avançadas - Pivot, Melt, Merge

In [ ]:
# Pivot Table
pivot_vendas = pd.pivot_table(
    df_vendas,
    values='Receita',
    index='Regiao',
    columns='Produto',
    aggfunc='sum',
    fill_value=0
)

print("Pivot Table - Receita por Região e Produto:")
print(pivot_vendas.round(2))

In [ ]:
# Aplicar função customizada
def classificar_receita(receita):
    if receita < 100000:
        return 'Baixa'
    elif receita < 300000:
        return 'Média'
    else:
        return 'Alta'

df_vendas['ClasseReceita'] = df_vendas['Receita'].apply(classificar_receita)

print("Distribuição por classe de receita:")
print(df_vendas['ClasseReceita'].value_counts())

In [ ]:
# String operations
df_vendas['Regiao_Upper'] = df_vendas['Regiao'].str.upper()
df_vendas['Produto_Lower'] = df_vendas['Produto'].str.lower()
df_vendas['Tem_Norte'] = df_vendas['Regiao'].str.contains('Norte')

print("Registros da região Norte:")
print(df_vendas[df_vendas['Tem_Norte']].groupby('Regiao')['Receita'].sum())

<a id='modulo3'></a>
# 📊 Módulo 3 – Visualização e Análise Exploratória de Dados

Visualização é parte essencial da ciência de dados.  
Neste módulo utilizaremos **Matplotlib**, **Seaborn** e **Plotly** para compreender padrões e distribuições.

## 3.1 Matplotlib - Visualizações Básicas

In [1]:
import matplotlib.pyplot as plt
import seaborn as sns

# Configuração de estilo
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 10

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
# Histograma - Distribuição de idades no Titanic
plt.figure(figsize=(10, 6))
plt.hist(df['Age'], bins=30, alpha=0.7, color='skyblue', edgecolor='black')
plt.axvline(df['Age'].mean(), color='red', linestyle='--', linewidth=2, 
            label=f'Média: {df["Age"].mean():.1f}')
plt.axvline(df['Age'].median(), color='green', linestyle='--', linewidth=2, 
            label=f'Mediana: {df["Age"].median():.1f}')
plt.xlabel('Idade')
plt.ylabel('Frequência')
plt.title('Distribuição de Idades - Titanic', fontsize=14, fontweight='bold')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

In [ ]:
# Gráfico de barras - Taxa de sobrevivência por classe
sobrevivencia_classe = df.groupby('Pclass')['Survived'].mean()

plt.figure(figsize=(10, 6))
bars = plt.bar(sobrevivencia_classe.index, sobrevivencia_classe.values, 
               color=['gold', 'silver', '#CD7F32'], edgecolor='black', alpha=0.8)

# Adicionar valores nas barras
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.1%}', ha='center', va='bottom', fontweight='bold')

plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Taxa de Sobrevivência', fontweight='bold')
plt.title('Taxa de Sobrevivência por Classe - Titanic', fontsize=14, fontweight='bold')
plt.xticks([1, 2, 3], ['1ª Classe', '2ª Classe', '3ª Classe'])
plt.ylim(0, 1)
plt.grid(True, alpha=0.3, axis='y')
plt.show()

In [ ]:
# Subplots - Múltiplos gráficos
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Gráfico 1: Distribuição de idade
axes[0, 0].hist(df['Age'], bins=30, alpha=0.7, color='skyblue', edgecolor='black')
axes[0, 0].set_title('Distribuição de Idades', fontweight='bold')
axes[0, 0].set_xlabel('Idade')
axes[0, 0].set_ylabel('Frequência')

# Gráfico 2: Distribuição de tarifas
axes[0, 1].hist(df['Fare'], bins=30, alpha=0.7, color='lightcoral', edgecolor='black')
axes[0, 1].set_title('Distribuição de Tarifas', fontweight='bold')
axes[0, 1].set_xlabel('Tarifa')
axes[0, 1].set_ylabel('Frequência')

# Gráfico 3: Contagem por classe
df['Pclass'].value_counts().sort_index().plot(kind='bar', ax=axes[1, 0], 
                                               color='lightgreen', edgecolor='black')
axes[1, 0].set_title('Passageiros por Classe', fontweight='bold')
axes[1, 0].set_xlabel('Classe')
axes[1, 0].set_ylabel('Quantidade')
axes[1, 0].set_xticklabels(['1ª Classe', '2ª Classe', '3ª Classe'], rotation=0)

# Gráfico 4: Taxa de sobrevivência por sexo
df.groupby('Sex')['Survived'].mean().plot(kind='bar', ax=axes[1, 1], 
                                          color=['lightblue', 'pink'], edgecolor='black')
axes[1, 1].set_title('Taxa de Sobrevivência por Sexo', fontweight='bold')
axes[1, 1].set_xlabel('Sexo')
axes[1, 1].set_ylabel('Taxa de Sobrevivência')
axes[1, 1].set_xticklabels(['Feminino', 'Masculino'], rotation=0)

plt.tight_layout()
plt.show()

## 3.2 Seaborn - Visualizações Estatísticas

In [ ]:
# Box Plot - Distribuição de idade por classe e sobrevivência
plt.figure(figsize=(12, 6))
sns.boxplot(x='Pclass', y='Age', hue='Survived', data=df, palette='Set2')
plt.title('Distribuição de Idade por Classe e Sobrevivência', fontsize=14, fontweight='bold')
plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Idade', fontweight='bold')
plt.legend(title='Sobreviveu', labels=['Não', 'Sim'])
plt.show()

In [ ]:
# Violin Plot
plt.figure(figsize=(12, 6))
sns.violinplot(x='Pclass', y='Fare', hue='Sex', data=df, split=True, palette='muted')
plt.title('Distribuição de Tarifas por Classe e Sexo', fontsize=14, fontweight='bold')
plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Tarifa', fontweight='bold')
plt.legend(title='Sexo')
plt.show()

In [ ]:
# Count Plot
plt.figure(figsize=(12, 6))
sns.countplot(x='Pclass', hue='Survived', data=df, palette='viridis')
plt.title('Contagem de Passageiros por Classe e Sobrevivência', fontsize=14, fontweight='bold')
plt.xlabel('Classe', fontweight='bold')
plt.ylabel('Contagem', fontweight='bold')
plt.legend(title='Sobreviveu', labels=['Não', 'Sim'])
plt.show()

In [ ]:
# Heatmap de correlação
plt.figure(figsize=(10, 8))
correlacao = df[['Pclass', 'Age', 'Fare', 'Survived']].corr()
sns.heatmap(correlacao, annot=True, cmap='coolwarm', center=0, 
            square=True, linewidths=1, cbar_kws={"shrink": 0.8})
plt.title('Matriz de Correlação - Titanic', fontsize=14, fontweight='bold')
plt.show()

## 3.3 Visualizações com Dados de Vendas

In [ ]:
# Evolução temporal de vendas
vendas_mensais = df_vendas.groupby(df_vendas['Data'].dt.to_period('M'))['Receita'].sum()
vendas_mensais.index = vendas_mensais.index.to_timestamp()

plt.figure(figsize=(15, 6))
plt.plot(vendas_mensais.index, vendas_mensais.values, marker='o', linewidth=2)
plt.fill_between(vendas_mensais.index, vendas_mensais.values, alpha=0.3)
plt.title('Evolução Mensal de Receita', fontsize=14, fontweight='bold')
plt.xlabel('Data', fontweight='bold')
plt.ylabel('Receita', fontweight='bold')
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

In [ ]:
# Gráfico de barras horizontal - Receita por região
receita_regiao = df_vendas.groupby('Regiao')['Receita'].sum().sort_values()

plt.figure(figsize=(10, 6))
bars = plt.barh(receita_regiao.index, receita_regiao.values, 
                color=sns.color_palette('husl', len(receita_regiao)))

# Adicionar valores
for i, (idx, val) in enumerate(receita_regiao.items()):
    plt.text(val, i, f' R$ {val:,.0f}', va='center', fontweight='bold')

plt.title('Receita Total por Região', fontsize=14, fontweight='bold')
plt.xlabel('Receita (R$)', fontweight='bold')
plt.ylabel('Região', fontweight='bold')
plt.grid(True, alpha=0.3, axis='x')
plt.tight_layout()
plt.show()

In [ ]:
# Gráfico de pizza - Participação por produto
vendas_produto = df_vendas.groupby('Produto')['Receita'].sum()

plt.figure(figsize=(10, 8))
colors = sns.color_palette('pastel')
plt.pie(vendas_produto.values, labels=vendas_produto.index, autopct='%1.1f%%',
        startangle=90, colors=colors, wedgeprops={'edgecolor': 'black'})
plt.title('Participação de Cada Produto na Receita Total', fontsize=14, fontweight='bold')
plt.axis('equal')
plt.show()

In [ ]:
# Heatmap - Receita por região e produto
pivot_reg_prod = pd.pivot_table(
    df_vendas, 
    values='Receita', 
    index='Regiao', 
    columns='Produto', 
    aggfunc='sum'
)

plt.figure(figsize=(12, 6))
sns.heatmap(pivot_reg_prod, annot=True, fmt='.0f', cmap='YlOrRd', 
            linewidths=0.5, cbar_kws={'label': 'Receita'})
plt.title('Receita por Região e Produto', fontsize=14, fontweight='bold')
plt.xlabel('Produto', fontweight='bold')
plt.ylabel('Região', fontweight='bold')
plt.tight_layout()
plt.show()

## 3.4 Análise do Dataset de COVID

In [ ]:
# Carregar e preparar dados de COVID
df_covid = pd.read_csv("datasets/covid.csv")
df_covid['Data'] = pd.to_datetime(df_covid['Data'])

print("Dataset COVID-19:")
print(df_covid.head())
print(f"\nPeríodo: {df_covid['Data'].min()} a {df_covid['Data'].max()}")

In [ ]:
# Evolução de casos por região
fig, axes = plt.subplots(2, 1, figsize=(15, 10))

# Casos ao longo do tempo
for regiao in df_covid['Regiao'].unique():
    dados_regiao = df_covid[df_covid['Regiao'] == regiao]
    axes[0].plot(dados_regiao['Data'], dados_regiao['Casos'], 
                 marker='o', label=regiao, linewidth=2)

axes[0].set_title('Evolução de Casos de COVID-19 por Região', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Data', fontweight='bold')
axes[0].set_ylabel('Casos', fontweight='bold')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Óbitos ao longo do tempo
for regiao in df_covid['Regiao'].unique():
    dados_regiao = df_covid[df_covid['Regiao'] == regiao]
    axes[1].plot(dados_regiao['Data'], dados_regiao['Obitos'], 
                 marker='s', label=regiao, linewidth=2)

axes[1].set_title('Evolução de Óbitos por COVID-19 por Região', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Data', fontweight='bold')
axes[1].set_ylabel('Óbitos', fontweight='bold')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

In [ ]:
# Totais por região
totais_covid = df_covid.groupby('Regiao').agg({
    'Casos': 'sum',
    'Obitos': 'sum',
    'Vacinados': 'sum'
})

totais_covid['Taxa_Mortalidade'] = (totais_covid['Obitos'] / totais_covid['Casos'] * 100)
totais_covid['Taxa_Vacinacao'] = (totais_covid['Vacinados'] / totais_covid['Casos'] * 100)

print("Estatísticas Totais de COVID-19 por Região:")
print(totais_covid.round(2))

In [ ]:
# Visualização comparativa
fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Casos totais por região
totais_covid['Casos'].plot(kind='bar', ax=axes[0], color='steelblue', edgecolor='black')
axes[0].set_title('Total de Casos por Região', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Região', fontweight='bold')
axes[0].set_ylabel('Casos', fontweight='bold')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(True, alpha=0.3, axis='y')

# Taxa de mortalidade por região
totais_covid['Taxa_Mortalidade'].plot(kind='bar', ax=axes[1], color='crimson', edgecolor='black')
axes[1].set_title('Taxa de Mortalidade por Região (%)', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Região', fontweight='bold')
axes[1].set_ylabel('Taxa (%)', fontweight='bold')
axes[1].tick_params(axis='x', rotation=45)
axes[1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.show()

<a id='modulo4'></a>
# ⚙️ Módulo 4 – Análise Estatística e Machine Learning

Neste módulo exploramos análises estatísticas, testes de hipóteses e introdução a Machine Learning.

## 4.1 Estatística Descritiva

In [ ]:
from scipy import stats

# Análise estatística completa
def analise_estatistica(dados, nome_variavel):
    print(f"\n{'='*60}")
    print(f"Análise Estatística: {nome_variavel}")
    print(f"{'='*60}")
    
    print(f"\nMedidas de Tendência Central:")
    print(f"  Média: {np.mean(dados):.2f}")
    print(f"  Mediana: {np.median(dados):.2f}")
    print(f"  Moda: {stats.mode(dados, keepdims=True)[0][0]:.2f}")
    
    print(f"\nMedidas de Dispersão:")
    print(f"  Variância: {np.var(dados):.2f}")
    print(f"  Desvio Padrão: {np.std(dados):.2f}")
    print(f"  Amplitude: {np.max(dados) - np.min(dados):.2f}")
    print(f"  IQR: {np.percentile(dados, 75) - np.percentile(dados, 25):.2f}")
    
    print(f"\nMedidas de Posição:")
    print(f"  Mínimo: {np.min(dados):.2f}")
    print(f"  Q1 (25%): {np.percentile(dados, 25):.2f}")
    print(f"  Q2 (50%): {np.percentile(dados, 50):.2f}")
    print(f"  Q3 (75%): {np.percentile(dados, 75):.2f}")
    print(f"  Máximo: {np.max(dados):.2f}")
    
    print(f"\nMedidas de Forma:")
    print(f"  Assimetria (Skewness): {stats.skew(dados):.2f}")
    print(f"  Curtose (Kurtosis): {stats.kurtosis(dados):.2f}")

# Aplicar análise
analise_estatistica(df['Age'].dropna(), 'Idade dos Passageiros do Titanic')
analise_estatistica(df['Fare'].dropna(), 'Tarifa dos Passageiros do Titanic')

## 4.2 Testes de Hipóteses

In [ ]:
# Teste t para amostras independentes
# H0: Não há diferença na idade média entre sobreviventes e não sobreviventes

idade_sobreviventes = df[df['Survived'] == 1]['Age'].dropna()
idade_nao_sobreviventes = df[df['Survived'] == 0]['Age'].dropna()

t_stat, p_value = stats.ttest_ind(idade_sobreviventes, idade_nao_sobreviventes)

print("Teste t para Idade: Sobreviventes vs Não Sobreviventes")
print(f"Média - Sobreviventes: {idade_sobreviventes.mean():.2f}")
print(f"Média - Não Sobreviventes: {idade_nao_sobreviventes.mean():.2f}")
print(f"\nEstatística t: {t_stat:.4f}")
print(f"P-valor: {p_value:.4f}")

if p_value < 0.05:
    print("\nConclusão: Rejeitamos H0. Há diferença significativa nas idades.")
else:
    print("\nConclusão: Não rejeitamos H0. Não há diferença significativa.")

In [ ]:
# Teste Qui-Quadrado de Independência
# H0: Classe e Sobrevivência são independentes

from scipy.stats import chi2_contingency

tabela_contingencia = pd.crosstab(df['Pclass'], df['Survived'])
print("Tabela de Contingência - Classe x Sobrevivência:")
print(tabela_contingencia)

chi2, p_value, dof, expected = chi2_contingency(tabela_contingencia)

print(f"\nEstatística Qui-Quadrado: {chi2:.4f}")
print(f"P-valor: {p_value:.4f}")
print(f"Graus de liberdade: {dof}")

if p_value < 0.05:
    print("\nConclusão: Rejeitamos H0. Classe e sobrevivência NÃO são independentes.")
else:
    print("\nConclusão: Não rejeitamos H0. Não há evidência de dependência.")

In [ ]:
# ANOVA - Comparação de múltiplos grupos
# H0: A média de tarifa é igual para todas as classes

classe1 = df[df['Pclass'] == 1]['Fare'].dropna()
classe2 = df[df['Pclass'] == 2]['Fare'].dropna()
classe3 = df[df['Pclass'] == 3]['Fare'].dropna()

f_stat, p_value = stats.f_oneway(classe1, classe2, classe3)

print("ANOVA - Tarifa por Classe")
print(f"Média Classe 1: {classe1.mean():.2f}")
print(f"Média Classe 2: {classe2.mean():.2f}")
print(f"Média Classe 3: {classe3.mean():.2f}")
print(f"\nEstatística F: {f_stat:.4f}")
print(f"P-valor: {p_value:.4f}")

if p_value < 0.05:
    print("\nConclusão: Rejeitamos H0. Há diferença significativa nas tarifas entre classes.")
else:
    print("\nConclusão: Não rejeitamos H0. Não há diferença significativa.")

In [ ]:
# Teste de Normalidade
stat_shapiro, p_shapiro = stats.shapiro(df['Age'].dropna())

print("Teste de Normalidade (Shapiro-Wilk) - Idade")
print(f"Estatística: {stat_shapiro:.4f}")
print(f"P-valor: {p_shapiro:.4f}")

if p_shapiro < 0.05:
    print("\nConclusão: Rejeitamos H0. Os dados NÃO seguem distribuição normal.")
else:
    print("\nConclusão: Não rejeitamos H0. Os dados seguem distribuição normal.")

## 4.3 Correlação e Regressão

In [ ]:
# Análise de correlação
print("Correlações (Pearson):")
print(f"Idade vs Tarifa: {df['Age'].corr(df['Fare']):.4f}")
print(f"Classe vs Sobrevivência: {df['Pclass'].corr(df['Survived']):.4f}")

# Correlação de Spearman (não linear)
spearman_corr, spearman_p = stats.spearmanr(df['Pclass'], df['Survived'])
print(f"\nCorrelação de Spearman (Classe vs Sobrevivência): {spearman_corr:.4f}")
print(f"P-valor: {spearman_p:.4f}")

In [ ]:
# Regressão Linear Simples
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Preparar dados (remover NaN)
dados_regressao = df[['Age', 'Fare']].dropna()
X = dados_regressao[['Age']].values
y = dados_regressao['Fare'].values

# Criar e treinar modelo
modelo_lr = LinearRegression()
modelo_lr.fit(X, y)

# Predições
y_pred = modelo_lr.predict(X)

# Métricas
print("Regressão Linear: Idade → Tarifa")
print(f"Intercepto: {modelo_lr.intercept_:.2f}")
print(f"Coeficiente: {modelo_lr.coef_[0]:.2f}")
print(f"\nR² Score: {r2_score(y, y_pred):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y, y_pred)):.2f}")
print(f"MAE: {mean_absolute_error(y, y_pred):.2f}")

In [ ]:
# Visualização da regressão
plt.figure(figsize=(10, 6))
plt.scatter(X, y, alpha=0.5, label='Dados reais')
plt.plot(X, y_pred, color='red', linewidth=2, label='Linha de regressão')
plt.xlabel('Idade', fontweight='bold')
plt.ylabel('Tarifa', fontweight='bold')
plt.title(f'Regressão Linear: Idade vs Tarifa (R² = {r2_score(y, y_pred):.3f})', 
          fontsize=14, fontweight='bold')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

## 4.4 Machine Learning - Classificação

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Preparar dados para classificação
df_ml = df[['Pclass', 'Sex', 'Age', 'Fare', 'Survived']].copy()
df_ml = df_ml.dropna()

# Encoding de variável categórica
df_ml['Sex_encoded'] = df_ml['Sex'].map({'Masculino': 0, 'Feminino': 1})

# Features e target
X = df_ml[['Pclass', 'Sex_encoded', 'Age', 'Fare']]
y = df_ml['Survived']

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
                                                      random_state=42, stratify=y)

# Normalização
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Dados de treino: {X_train.shape}")
print(f"Dados de teste: {X_test.shape}")
print(f"\nDistribuição da classe (treino):")
print(y_train.value_counts(normalize=True))

In [ ]:
# Modelo 1: Regressão Logística
modelo_lr = LogisticRegression(random_state=42)
modelo_lr.fit(X_train_scaled, y_train)

y_pred_lr = modelo_lr.predict(X_test_scaled)
acuracia_lr = accuracy_score(y_test, y_pred_lr)

print("="*60)
print("REGRESSÃO LOGÍSTICA")
print("="*60)
print(f"\nAcurácia: {acuracia_lr:.3f}")
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred_lr, 
                          target_names=['Não Sobreviveu', 'Sobreviveu']))

# Matriz de confusão
cm_lr = confusion_matrix(y_test, y_pred_lr)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues', 
            xticklabels=['Não Sobreviveu', 'Sobreviveu'],
            yticklabels=['Não Sobreviveu', 'Sobreviveu'])
plt.title('Matriz de Confusão - Regressão Logística', fontweight='bold')
plt.ylabel('Real', fontweight='bold')
plt.xlabel('Predito', fontweight='bold')
plt.show()

In [ ]:
# Modelo 2: Random Forest
modelo_rf = RandomForestClassifier(n_estimators=100, random_state=42)
modelo_rf.fit(X_train_scaled, y_train)

y_pred_rf = modelo_rf.predict(X_test_scaled)
acuracia_rf = accuracy_score(y_test, y_pred_rf)

print("="*60)
print("RANDOM FOREST")
print("="*60)
print(f"\nAcurácia: {acuracia_rf:.3f}")
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred_rf, 
                          target_names=['Não Sobreviveu', 'Sobreviveu']))

# Feature importance
importancias = pd.DataFrame({
    'Feature': X.columns,
    'Importância': modelo_rf.feature_importances_
}).sort_values('Importância', ascending=False)

print("\nImportância das Features:")
print(importancias)

# Visualizar importância
plt.figure(figsize=(10, 6))
sns.barplot(x='Importância', y='Feature', data=importancias, palette='viridis')
plt.title('Importância das Features - Random Forest', fontweight='bold')
plt.xlabel('Importância', fontweight='bold')
plt.ylabel('Feature', fontweight='bold')
plt.show()

In [ ]:
# Curva ROC
from sklearn.metrics import roc_curve, roc_auc_score

# Probabilidades
y_proba_lr = modelo_lr.predict_proba(X_test_scaled)[:, 1]
y_proba_rf = modelo_rf.predict_proba(X_test_scaled)[:, 1]

# Calcular ROC
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_proba_lr)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_proba_rf)

auc_lr = roc_auc_score(y_test, y_proba_lr)
auc_rf = roc_auc_score(y_test, y_proba_rf)

# Plotar
plt.figure(figsize=(10, 6))
plt.plot(fpr_lr, tpr_lr, linewidth=2, label=f'Regressão Logística (AUC = {auc_lr:.3f})')
plt.plot(fpr_rf, tpr_rf, linewidth=2, label=f'Random Forest (AUC = {auc_rf:.3f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random (AUC = 0.5)')
plt.xlabel('Taxa de Falsos Positivos', fontweight='bold')
plt.ylabel('Taxa de Verdadeiros Positivos', fontweight='bold')
plt.title('Curva ROC - Comparação de Modelos', fontsize=14, fontweight='bold')
plt.legend(loc='lower right')
plt.grid(True, alpha=0.3)
plt.show()

In [ ]:
# Validação Cruzada
from sklearn.model_selection import cross_val_score, KFold

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# Regressão Logística
scores_lr = cross_val_score(modelo_lr, X_train_scaled, y_train, 
                             cv=kfold, scoring='accuracy')
print("Validação Cruzada - Regressão Logística")
print(f"Scores: {scores_lr}")
print(f"Média: {scores_lr.mean():.3f} (+/- {scores_lr.std():.3f})")

# Random Forest
scores_rf = cross_val_score(modelo_rf, X_train_scaled, y_train, 
                             cv=kfold, scoring='accuracy')
print("\nValidação Cruzada - Random Forest")
print(f"Scores: {scores_rf}")
print(f"Média: {scores_rf.mean():.3f} (+/- {scores_rf.std():.3f})")

## 4.5 Clustering - Análise de Filmes

In [ ]:
# Carregar dataset de filmes
df_filmes = pd.read_csv("datasets/filmes.csv")
print("Dataset de Filmes:")
print(df_filmes.head())
print(f"\nTotal de filmes: {len(df_filmes)}")
print(f"Gêneros únicos: {df_filmes['Genero'].unique()}")

In [ ]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Preparar dados para clustering
X_cluster = df_filmes[['Ano', 'Nota', 'Popularidade']].copy()

# Normalizar
scaler_cluster = StandardScaler()
X_cluster_scaled = scaler_cluster.fit_transform(X_cluster)

# Método do cotovelo
inertias = []
silhouette_scores = []
K_range = range(2, 11)

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_cluster_scaled)
    inertias.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(X_cluster_scaled, kmeans.labels_))

# Visualizar método do cotovelo
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

axes[0].plot(K_range, inertias, 'bo-', linewidth=2)
axes[0].set_xlabel('Número de Clusters', fontweight='bold')
axes[0].set_ylabel('Inércia', fontweight='bold')
axes[0].set_title('Método do Cotovelo', fontweight='bold')
axes[0].grid(True, alpha=0.3)

axes[1].plot(K_range, silhouette_scores, 'ro-', linewidth=2)
axes[1].set_xlabel('Número de Clusters', fontweight='bold')
axes[1].set_ylabel('Silhouette Score', fontweight='bold')
axes[1].set_title('Silhouette Score por Número de Clusters', fontweight='bold')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

In [ ]:
# Aplicar K-Means com k=4
kmeans_final = KMeans(n_clusters=4, random_state=42, n_init=10)
df_filmes['Cluster'] = kmeans_final.fit_predict(X_cluster_scaled)

print(f"Silhouette Score: {silhouette_score(X_cluster_scaled, df_filmes['Cluster']):.3f}")
print("\nDistribuição de filmes por cluster:")
print(df_filmes['Cluster'].value_counts().sort_index())

print("\nCaracterísticas médias por cluster:")
print(df_filmes.groupby('Cluster')[['Ano', 'Nota', 'Popularidade']].mean())

In [ ]:
# Visualizar clusters
fig = plt.figure(figsize=(15, 5))

# Plot 1: Nota vs Popularidade
ax1 = fig.add_subplot(131)
scatter1 = ax1.scatter(df_filmes['Nota'], df_filmes['Popularidade'], 
                        c=df_filmes['Cluster'], cmap='viridis', alpha=0.6)
ax1.set_xlabel('Nota', fontweight='bold')
ax1.set_ylabel('Popularidade', fontweight='bold')
ax1.set_title('Clusters: Nota vs Popularidade', fontweight='bold')
plt.colorbar(scatter1, ax=ax1, label='Cluster')

# Plot 2: Ano vs Nota
ax2 = fig.add_subplot(132)
scatter2 = ax2.scatter(df_filmes['Ano'], df_filmes['Nota'], 
                        c=df_filmes['Cluster'], cmap='viridis', alpha=0.6)
ax2.set_xlabel('Ano', fontweight='bold')
ax2.set_ylabel('Nota', fontweight='bold')
ax2.set_title('Clusters: Ano vs Nota', fontweight='bold')
plt.colorbar(scatter2, ax=ax2, label='Cluster')

# Plot 3: Ano vs Popularidade
ax3 = fig.add_subplot(133)
scatter3 = ax3.scatter(df_filmes['Ano'], df_filmes['Popularidade'], 
                        c=df_filmes['Cluster'], cmap='viridis', alpha=0.6)
ax3.set_xlabel('Ano', fontweight='bold')
ax3.set_ylabel('Popularidade', fontweight='bold')
ax3.set_title('Clusters: Ano vs Popularidade', fontweight='bold')
plt.colorbar(scatter3, ax=ax3, label='Cluster')

plt.tight_layout()
plt.show()

<a id='modulo5'></a>
# 🎓 Módulo 5 – Projeto Final Integrado

Neste módulo, você deve escolher um dos datasets disponíveis e desenvolver uma análise completa.

## Datasets Disponíveis

1. **titanic.csv** - Análise de sobrevivência de passageiros
2. **vendas.csv** - Análise de vendas regionais e desempenho de produtos
3. **ibge_populacao.csv** - Indicadores populacionais e variação temporal
4. **covid.csv** - Casos, óbitos e taxas de vacinação
5. **filmes.csv** - Notas médias, popularidade e gêneros

## Estrutura do Projeto Final

Seu projeto deve incluir:

### 1. Introdução
- Contexto do problema
- Objetivos da análise
- Perguntas que serão respondidas

### 2. Exploração dos Dados
- Carregamento e visualização inicial
- Estatísticas descritivas
- Identificação de valores ausentes e outliers

### 3. Limpeza e Preparação
- Tratamento de valores ausentes
- Remoção de duplicatas
- Criação de novas features (feature engineering)
- Transformações necessárias

### 4. Análise Exploratória (EDA)
- Visualizações relevantes
- Análise de distribuições
- Identificação de padrões e tendências
- Análise de correlações

### 5. Análise Estatística
- Testes de hipóteses apropriados
- Análise de significância
- Intervalos de confiança

### 6. Modelagem (opcional)
- Modelo preditivo ou de clustering
- Avaliação de desempenho
- Interpretação dos resultados

### 7. Insights e Conclusões
- Principais descobertas
- Resposta às perguntas iniciais
- Recomendações baseadas na análise
- Limitações do estudo

### 8. Documentação
- Código bem comentado
- Explicações claras das escolhas metodológicas
- Referências utilizadas

## Exemplo de Estrutura - Análise de População IBGE

In [ ]:
# Carregar dados
df_ibge = pd.read_csv("datasets/ibge_populacao.csv")

print("Dataset IBGE - População:")
print(df_ibge.head())
print(f"\nPeríodo: {df_ibge['Ano'].min()} a {df_ibge['Ano'].max()}")
print(f"\nRegiões: {df_ibge['Regiao'].unique()}")

In [ ]:
# Análise por região
print("População Total por Região (2024):")
pop_2024 = df_ibge[df_ibge['Ano'] == df_ibge['Ano'].max()]
print(pop_2024.sort_values('Populacao', ascending=False))

# Crescimento populacional
pivot_ibge = df_ibge.pivot(index='Ano', columns='Regiao', values='Populacao')
print("\nCrescimento Populacional por Região:")
crescimento = ((pivot_ibge.loc[pivot_ibge.index.max()] - 
                pivot_ibge.loc[pivot_ibge.index.min()]) / 
               pivot_ibge.loc[pivot_ibge.index.min()] * 100)
print(crescimento.sort_values(ascending=False))

In [ ]:
# Visualização da evolução populacional
plt.figure(figsize=(15, 6))

for regiao in df_ibge['Regiao'].unique():
    dados_regiao = df_ibge[df_ibge['Regiao'] == regiao]
    plt.plot(dados_regiao['Ano'], dados_regiao['Populacao'], 
             marker='o', linewidth=2, label=regiao)

plt.title('Evolução Populacional por Região (2015-2024)', fontsize=14, fontweight='bold')
plt.xlabel('Ano', fontweight='bold')
plt.ylabel('População', fontweight='bold')
plt.legend(title='Região', loc='best')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

## Espaço para Seu Projeto Final

Use as células abaixo para desenvolver seu projeto final.

In [ ]:
# Seu código aqui


## ✅ Conclusão

Este notebook forneceu uma base técnica sólida em programação e manipulação de dados com Python, integrando:

- **Fundamentos de Python**: Estruturas de dados, funções, compreensões
- **NumPy**: Computação numérica eficiente
- **Pandas**: Manipulação e análise de dados tabulares
- **Visualização**: Matplotlib e Seaborn para insights visuais
- **Estatística**: Testes de hipóteses e análises estatísticas
- **Machine Learning**: Classificação, regressão e clustering

### Próximos Passos

1. Completar o projeto final escolhido
2. Explorar técnicas avançadas de feature engineering
3. Aprofundar em algoritmos de Machine Learning
4. Estudar Deep Learning e redes neurais
5. Desenvolver projetos próprios

### Recursos Adicionais

- Documentação oficial: [pandas.pydata.org](https://pandas.pydata.org)
- Scikit-learn: [scikit-learn.org](https://scikit-learn.org)
- Kaggle: [kaggle.com](https://kaggle.com) - datasets e competições

**Bons estudos e boa análise de dados!**